<?php

// call to hook_views_pre_execute to override the query for the groups browser
function planetmath_messages_view_views_pre_execute(&$view) {
   dd($view->name);
   if($view->name=="messages") {
     // This is a way to display the query, but I don't have a particularly
     // clear sense of how to *modify* the query
     dsm($view->build_info['query']->__toString()); 
      }
}

function planetmath_messages_menu() {
  $items = array();

  $items['talk'] = array(
      'title' => 'Talk',
      'type' => MENU_CALLBACK,
      'page callback' => 'planetmath_messages_show',
      'page arguments' => array(1),
      'access arguments' => array('create correction content')
  );

  return $items;
}

function planetmath_messages_get_all_messages(){

  $firstQuery = db_select('comment','c');
  $firstQuery->addField('c', 'cid', 'my_id');
  $firstQuery->addField('c', 'subject', 'title');
  $firstQuery->addField('c', 'uid', 'uid');
  $firstQuery->addField('c', 'changed', 'changed');
  $firstQuery->addField('c', 'created', 'created');
  $firstQuery->addField('c', 'name', 'username');
  $firstQuery->join('node','n','n.nid = c.nid');
  $firstQuery->leftJoin('field_data_comment_body','fcb','c.cid = fcb.entity_id');
  $firstQuery->join('users','u','u.uid = c.uid');
  $firstQuery->addField('n', 'nid', 'nid');
  $firstQuery->addField('n', 'type', 'my_type');
  $firstQuery->addField('fcb', 'comment_body_value', 'body');

  // Note that the *order* in which these fields are added
  // matters in terms of what we get back from the database.
  $secondQuery = db_select('node','n');
  $secondQuery->addField('n', 'nid', 'my_id');
  $secondQuery->addField('n', 'title', 'title');
  $secondQuery->addField('n', 'uid', 'uid');
  $secondQuery->addField('n', 'changed', 'changed');
  $secondQuery->addField('n', 'created', 'created');
  $secondQuery->condition('type','forum', '=');
  $secondQuery->leftJoin('field_data_body','fdb','n.nid = fdb.entity_id');
  $secondQuery->join('users','u','u.uid = n.uid');
  $secondQuery->addField('u', 'name', 'username');
  $secondQuery->addField('n', 'nid', 'nid');
  $secondQuery->addField('n', 'type', 'my_type');
  $secondQuery->addField('fdb', 'body_value', 'body');
  $secondQuery->extend('PagerDefault')->limit(20);
  $secondQuery->extend('TableSort');

  // union to the first query here, order everything, and set the fancy UI stuff
 $result = $secondQuery->union($firstQuery, 'UNION ALL')
   ->execute();

  return $result;
}

function planetmath_messages_show($nid){
  global $base_url;
  //dd('in the show messages function');
  //dd($nid);
  $count1=db_query("SELECT COUNT(nid) as count FROM comment")->fetchObject();
  $count2=db_query("SELECT COUNT(nid) as count FROM node WHERE type = 'forum'")->fetchObject();
  if($count1->count > 0 || $count2->count > 0) {
    $messages = planetmath_messages_get_all_messages();

    // start with a couple columns for now
    $header = array(array('data' => 'Title', 
			  'field' => 'nid'),
		    array('data' => "Author", 
			  'field' => 'username'),
		    array('data' => "Date", 
			  'field' => 'created'),
		    );

    $rows = array();

    foreach ($messages as $message) {
      dd("MESSAGE");
      dd($message);

      $rows[] = array(
		      array('data' => l($message->title, 'node/' . $message->nid), 
			    'field' => 'title'),
		      array('data' => l($message->username, 'user/' . $message->uid), 
			    'field' => 'username'),
		      array('data' => format_date($message->created), 
			    'field' => 'created'),
		      );
    }

    dd("ROWS");
    dd($rows);

    return theme('table', array(
				'header' => $header,
				'rows' => $rows
				)) 
           . theme('pager');
  } else {
    drupal_set_message("Go ahead and create some messages.  They will show up in the listing in due course!");
    drupal_goto('forum');
  }
}


