<?php

/**
 * Implementing hook_menu()
 */
function mmt_menu() {
    $items['mmt/setup'] = array(
	  'title' => "Setup MMT",
	  'page callback' => 'mmt_setup',
	  'access callback' => 'mmt_setup_access',
	  'menu_name' => 'navigation'
	  );

    $items['mmt/autoload'] = array(
    'title' => "AutoLoad",
    'page callback' => 'mmt_create_nodes',
    'access callback' => 'mmt_setup_access',
    'menu_name' => 'navigation'
    );

  $items['mmt/archives'] = array(
    'title' => "Archive Callback",
	  'page callback' => 'mmt_archives',
	  'access callback' => true,
    'menu_name' => 'main-menu',
    'weight' => 10,
    'type' => MENU_CALLBACK,
	);

    return $items;
  }

function mmt_setup_access() {
  global $user;
  if ($user-> uid == 1) {//only admin has rights 
    return true;
  } else {
	return false;
  }
}


function mmt_archives() {
  //TODO change generation mode for this page
  $htmlText = '
	The archives page contains a collection of flexiformal mathematical repositories that are made available in the OAFF. 
	Currently, this includes the following: 
    <ul>
     <li> <a href="?q=/http%3A//docs.omdoc.org/urtheories">urtheories</a> - formal foundations</li>
     <li> <a href="?q=/http%3A//docs.omdoc.org/latin">LATIN</a> - logic atlas</li>
     <li> <a href="?q=/http%3A//www.openmath.org">OpenMath</a> - a content dictionary with Scala-based computational semantics </li>
     <li> <a href="?q=/http%3A//docs.omdoc.org/smglo">SMGlo</a> - a semantic glossary of mathematics (in progress) </li>

    </ul>
	';
  return $htmlText;
}

/*
 * converts (virtual) filesystem filepath to MMT document path
 */
function mmt_get_doc_path($file) {
  $archives = array(
    'smglo' => 'http://docs.omdoc.org/smglo/',
    'latin' => 'http://docs.omdoc.org/latin/',
    'urtheories' => 'http://docs.omdoc.org/urtheories/' ,
    'openmath' => 'http://www.openmath.org/',
    ); //hardcoded for now, get be gotten from MMT using archive name

  //getting archive and fragment path
  $parts = explode('/', $file); //format is <archive-name>/source/<fragment path>
  $base = $archives[$parts[0]];
  $fragParts = array_slice($parts, 2);
  $srcFrag = join('/', $fragParts);

  //changing extension to .omdoc since that is the path of compilation result
  $parts = explode('.', $srcFrag);
  if (count($parts) > 1) { 
    $parts[count($parts) - 1] = "omdoc"; 
  }
  $srcFrag = join(".", $parts); 

  //return MMT doc path
  return $base . $srcFrag;
}

function mmt_get_format($location) {
  $parts = explode('.', $location);
  $ext = $parts[count($parts) - 1];
  return $ext;  
}


/**
 * Initialize MMT, loads css and js files and uses jobad API
 */
function mmt_initialize() {
	/**
     * CSS
     */
    $mmtPath = drupal_get_path('module', 'mmt');
    $mmtUrl = variable_get('mmtUrl');  
 
    //drupal_add_css($mmtPath . '/resources/mmt-web/css/omdoc/omdoc-default.css');
    drupal_add_css($mmtPath . '/resources/mmt-web/css/mmt.css', array('weight' => PHP_INT_MAX, 'every_page' => false));
   // drupal_add_css($mmtPath . '/resources/mmt-web/css/browser.css');
    drupal_add_css($mmtPath . '/resources/mmt-web/script/codemirror2/lib/codemirror.css');
    //drupal_add_css($mmtPath . '/resources/mmt-web/css/JOBAD.css');
    drupal_add_css($mmtPath . '/resources/mmt-web/css/jquery/jquery-ui.css');
    
    /**
     * JavaScript
     */
    drupal_add_js('var mmtUrl = "' . $mmtUrl . '";', 'inline');
    
  
    jobad_add_module($mmtPath . '/resources/mmt-web/script/jobad/modules/planetary-navigation.js', "kwarc.mmt.planetary.navigation");
    jobad_add_module($mmtPath . '/resources/mmt-web/script/jobad/modules/hovering.js', "kwarc.mmt.hovering");
    jobad_add_module($mmtPath . '/resources/mmt-web/script/jobad/modules/interactive-viewing.js', "kwarc.mmt.intvw");
  //  jobad_add_module($mmtPath . '/resources/mmt-web/script/jobad/modules/edit.js', "kwarc.mmt.editing");
  //  jobad_add_module($mmtPath . '/resources/mmt-web/script/jobad/modules/folding.js', "kwarc.mmt.folding");
    $instName = jobad_initialize();
    //codemirror (editor)
    drupal_add_js($mmtPath . '/resources/mmt-web/script/codemirror2/lib/codemirror.js', 'file');
    drupal_add_js($mmtPath . '/resources/mmt-web/script/codemirror2/mode/lf/lf.js', 'file');  
    //tree 
    drupal_add_js($mmtPath . '/resources/mmt-web/script/tree/jquery.hotkeys.js', 'file');
    drupal_add_js($mmtPath . '/resources/mmt-web/script/tree/jquery.jstree.js', 'file');
    //mmt js libs
    drupal_add_js($mmtPath . '/resources/mmt-web/script/jobad/mmt-html.js', 'file', array('cache' => false));
    drupal_add_js($mmtPath . '/resources/mmt-web/script/jobad/mathml.js', 'file', array('cache' => false));
    //modules
    return $instName;
}

/**  MMT Filters */
/*
 * filter hooks for handling content formats
 */
function mmt_filter_info() {
  $filters = array();
  $filters['mmt-presentation'] = array(
    'title' => t('MMT Presentation filter'),
    'description' => t('The text will be rendered by MMT using a presentation style'),
    'process callback' => 'mmt_filter_presentation_process',
    'default settings' => array(
      'mmt_style' => 'http://cds.omdoc.org/styles/omdoc/mathml.omdoc?html5',
    ),
    'settings callback' => 'mmt_filter_presentation_settings',
 //   'tips callback' => '_mmt_filter_presentation_tips',
  );
  $filters['mmt-compilation'] = array(
    'title' => t('MMT Compilation filter'),
    'description' => t('The text will be compiled by MMT to return MMT-OMDoc'),
    'process callback' => 'mmt_filter_compilation_process',
    'default settings' => array(
      'mmt_format' => 'mmt',
    ),
    'settings callback' => 'mmt_filter_compilation_settings',
 //   'tips callback' => '_mmt_filter_presentation_tips',
  );

  return $filters;
}

function mmt_filter_presentation_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  global $filter_context;
  $dpath = $filter_context['mmt']['dpath'];
  $style = $filter->settings['mmt_style'];
  $result = mmt_get_presentation($dpath, $text, $style);
  return $result;
}


function mmt_filter_compilation_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  global $filter_context;
  $dpath = $filter_context['mmt']['dpath'];
  $format = $filter->settings['mmt_format'];
  $result = mmt_get_compiled($text, $dpath, $format);
  return $result;
}

function mmt_filter_presentation_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['mmt_style'] = array(
    '#type' => 'textfield',
    '#title' => t('MMT Presentation Style'),
    '#default_value' => isset($filter->settings['mmt_style']) ? $filter->settings['mmt_style'] : $defaults['mmt_style'],
    '#description' => t('The URI or name of the style used by MMT to generate presentation for MMT/OMDoc documents'),
  );
  return $settings;
}

function mmt_filter_compilation_settings($form, $form_state, $filter, $format, $defaults) {
  $settings['mmt_format'] = array(
    '#type' => 'textfield',
    '#title' => t('Input Format for MMT to compile'),
    '#default_value' => isset($filter->settings['mmt_format']) ? $filter->settings['mmt_format'] : $defaults['mmt_format'],
    '#description' => t('The format of the text sent to MMT to be compiled into MMT/OMDoc'),
  );
  return $settings;
}

/** Other Hooks */

/**
 * implements hook_form_alter, adds URI field to mmt-specific forms
 */
function mmt_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'mmt_module_node_form') {
    $form['uri'] = array(
      '#type' => 'textfield',
      '#title' => t('MMT URI'),
	  );

 
	  if(array_key_exists('nid', $form_state['node'])) { //editing existing node
	  	$nid = $form_state['node']->nid;
	  	$result = db_select('mmturi', 'm')->fields('m',array('uri'))->condition('nid', $nid, '=')->execute()->fetchAssoc();
	  	$uri = $result['uri'];
	  	$form['uri']['#default_value'] = $uri;
	  	$form['uri']['#disabled'] = TRUE;
	  }
  }
  
  if ($form_id == 'mmtdoc_node_form') {

    $form['body'] = array(
      '#type' => 'textarea',
      '#title' => t('Body'),
    );
 
    if(array_key_exists('nid', $form_state['node'])) { //editing existing node
      $nid = $form_state['node']->nid;
      $result = db_select('mmtdoc', 'm')->fields('m',array('location'))->condition('nid', $nid, '=')->execute()->fetchAssoc();
      $location = $result['location'];
      $content = planetary_repo_local_load($location);

      $form['body']['#default_value'] = $content;
      $ext = mmt_get_format($location);
      if ($ext == 'elf') {
        $form['body']['#disabled'] = TRUE;
      }
    }
  }
}

/**
 * implements hook_node_insert, inserts URI to mmturi table, for mmt-specific nodes
 */
function mmt_node_insert($node) {
  if ($node->type == 'mmt_module') {
    db_insert('mmturi')->fields(array(
       'nid' => $node->nid,
       'uri' => $node->uri))->execute();
  }

  if ($node->type == 'mmtdoc') {
    db_insert('mmtdoc')->fields(array(
       'nid' => $node->nid,
       'location' => $node->field_external['und']['0']['location']))->execute();
  }

  if ($node->type == 'glossary' || $node->type == 'mmtdoc') {
    $nid = $node->nid;
    $dpath = $node->field_external['und']['0']['dpath']['value'];
    mmt_save_path($nid, $dpath);
  }
  

}

/**
 *  Creates nodes for all documents in planetary_repo path where there is a mmt-connected content type 
 * associated with that format (based on file extension).  
 */
function mmt_create_nodes() {
  $formats = array(
    'smglo' =>  'tex',
    'latin' => 'elf',
    'urtheories' => 'mmt',
    'openmath' => 'mmt',
    );

  $node_types = array(
    'tex' => 'glossary', 
    'elf' => 'mmtdoc', //lf format
    'mmt' => 'mmtdoc', //mmt format
  );

  $res = planetary_repo_local_list("");
  foreach ($res as $file) {
    if (array_key_exists($file, $formats)) {
      $format = $formats[$file];
      _mmt_create_nodes($file . "/source", $format, $node_types[$format]);

    }
  }

  return "Success";
}

function _mmt_create_nodes($path, $format, $node_type) {
  $res = planetary_repo_local_list($path);
  $title = $path;
  $body = '';
  foreach ($res as $file) {
    $fpath = $path . "/" .$file;
    if($file[0] != '.') {
      if (planetary_repo_is_dir($fpath)) {         
        _mmt_create_nodes($fpath, $format, $node_type);
        $dpath = mmt_get_doc_path($fpath);          
        $body .= '<p><a href="?q='. drupal_encode_path($dpath) .'">' . $file . "</a></p>\n";
      } else {
        $parts = explode('.', $file);
        $ext = $parts[count($parts) - 1];
        if ($ext == $format) {
          $module = $parts[0];
          $lang = 'und'; //default
          if (count($parts) == 3) {
            $lang = $parts[1];
          }

          $dpath = mmt_get_doc_path($fpath);          
          mmt_create_node($module, $lang, $format, $dpath, $fpath, $node_type);        
          $body .= '<p><a href="?q='. drupal_encode_path($dpath) .'">' . $file . "</a></p>\n";
        }
      }
    }
  }
  $menupath = mmt_get_doc_path($path);
  $nid = mmt_create_article($title, $body);
  mmt_save_path($nid, $menupath);
}

function mmt_create_node($module, $lang, $format, $dpath, $location, $node_type) {
  $title = $module;
  $newnode = (object) array(
   'type' => $node_type,
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 2,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => $lang
  );

  $newnode->title = $title;
  $newnode->field_external['und']['0']['location'] = $location;
  $newnode->field_external['und']['0']['path'] = $module;
  $newnode->field_external['und']['0']['filter'] = $format;
  $newnode->field_external['und']['0']['dpath']['value'] = $dpath;
   
  node_object_prepare($newnode);//necessary ?
  node_save($newnode);
  return $newnode->nid;
}

function mmt_create_article($title, $body) {
  $newnode = (object) array(
   'type' => 'article',
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 2,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => 'und'
  );
  $newnode->title = $title;
  $newnode->body['und'][0]['value'] = $body;
  $newnode->body['und'][0]['summary'] = $body;  
  $newnode->body['und'][0]['format'] = 'filtered_html';  

  node_object_prepare($newnode);//necessary ?
  node_save($newnode);
  return $newnode->nid;

}

/**
 * implements hook_node_load, loads URI from mmturi table, for mmt-specific nodes
 */
function mmt_node_load($nodes, $types) {
  $mmtNodes = array();
  //mmt_module
  foreach ($nodes as $node) {
    if ($node->type == 'mmt_module') {
      $mmtNodes[$node->nid] = $node;
    }
  }
  if (count($mmtNodes) > 0) { //something to do	
    $result = db_query('SELECT nid,uri FROM {mmturi} WHERE nid IN (:nids)', array(':nids' => array_keys($mmtNodes)));
    foreach ($result as $record) {
      $nodes[$record->nid]->uri = $record->uri; 
    }
  }
  //mmtdoc
  $docNodes = array();
  foreach ($nodes as $node) {
    if ($node->type == 'mmtdoc') {
      $docNodes[$node->nid] = $node;
    }
  }
  if (count($docNodes) > 0) { //something to do 
    $result = db_query('SELECT nid,location FROM {mmtdoc} WHERE nid IN (:nids)', array(':nids' => array_keys($docNodes)));
    foreach ($result as $record) {
      $nodes[$record->nid]->location = $record->location;       
    }

  }
}

/**
 * implements hook_node_view, renders mmt-specific nodes by loading html from MMT instance
 */
function mmt_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'mmt_module'  ) {
	  $inst_id = mmt_initialize();
 	  //getting pres from db
    $mmt_presentation = mmt_get_contentPres($node->uri);
    $node->content['mathml_body'] = array(
      '#markup' => '<div id=' . $inst_id . ' style="overflow:auto">' . $mmt_presentation . '</div>',
      '#weight' => 10,
    );
  }

  if ($node->type == 'mmtdoc') {
    $path = $node->location;
    $content = planetary_repo_local_load($path);
    //TODO now check markup
    global $filter_context;
    $filter_context = array();
    $filter_context['mmt']['dpath'] = mmt_get_doc_path($path);
    $markup = check_markup($content, 'mmt');
    $node->content['field_external'][0]['content']['#markup'] = $markup;      
  }

  if ($node->type == 'glossary' || $node->type == 'mmtdoc') {
    $inst_id = mmt_initialize();
    $content = $node->content['field_external'][0]['content']['#markup'];
    $node->content['field_external'][0]['content']['#markup'] = '<div id="' . $inst_id . '">' . $content . '</div>' ;
  }
}

function mmt_get_contentPres($path, $style = 'http://cds.omdoc.org/styles/omdoc/mathml.omdoc?html5') {
  $mmtUrl = variable_get('mmtUrl');
  $url = $mmtUrl . '/:planetary/getContentPres';
  $data = array('path' => $path, 'style' => $style);
  $options = array(
    'http' => array(
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ),
  );
  $context  = stream_context_create($options);
  $result = file_get_contents($url, false, $context);
  return $result;
}

function mmt_get_presentation($dpath, $body, $style = 'http://cds.omdoc.org/styles/omdoc/mathml.omdoc?html5') {
  $mmtUrl = variable_get('mmtUrl');
  $url = $mmtUrl . '/:planetary/getPresentation';
  $data = array('body' => $body, 'dpath' => $dpath, 'style' => $style);
  
  $options = array(
    'http' => array(
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ),
  );
  $context  = stream_context_create($options);
  $result = file_get_contents($url, false, $context);
  return $result;
}

function mmt_get_compiled($body, $dpath, $format) {
  $mmtUrl = variable_get('mmtUrl');
  $url = $mmtUrl . '/:planetary/getCompiled';
  $data = array('body' => $body, 'dpath' => $dpath, 'format' => $format);
  
  $options = array(
    'http' => array(
        'header'  => "Content-type: application/json\r\n",
        'method'  => 'POST',
        'content' => json_encode($data),
    ),
  );
  $context  = stream_context_create($options);
  $result = file_get_contents($url, false, $context);

  return $result;
}

function mmt_get_content($path) {
  $mmtUrl = variable_get('mmtUrl');
  $postPath = '???'; //default-for documents
  if (substr_count($path, '?') == 1) { //mmt module
    $postPath = '??';
  }
  $url = $mmtUrl . '/:mmt?' . $path . $postPath. '_present_' . 'xml';
  $content = file_get_contents($url);
  return $content;
}

/**
 * helper function to automatically create nodes in drupal by loading from an MMT instance (currently hardcoded)
 */
function mmt_setup() {
  $mmtUrl = variable_get('mmtUrl');
  $qUrl = $mmtUrl . '/:planetary/getPaths';
  //$qUrl = 'public/getPaths'; //quick hack for preloading mmt uris
  $result = file_get_contents($qUrl);
  drupal_set_message("Loading: ");
  mmt_load_nodes($result);
//  menu_build_tree('navigation');
  drupal_set_message("Success");
  return "";
}


function mmt_save_path($nid, $path) {
  if (substr($path, -1) == '/') {
    $path = substr($path, 0, -1);
  }
  
  $pathOpt = array(
    'source' => 'node/' . $nid,
    'alias' => $path,
  );
  path_save($pathOpt);
    /*
    //link for tree menu
    $menuOpt = array (
    'link_path' => drupal_get_normal_path($path),
        'link_title' => $uri[count($uri) - 1],
        'plid' => $plids_stack[count($plids_stack) - 1],
        'menu_name' => 'navigation',
    );
    $id = menu_link_save($menuOpt);
    drupal_set_message($alias);
    $mlids[] = $id;
    $plids_stack[] = $id;
    */
}

function mmt_load_nodes($pathsStr) {
  $lines = explode("\n", $pathsStr);
  $arch_item = array(
    'link_path' => drupal_get_normal_path('mmt/archives'),
    'link_title' => "Archives",
    'menu_name' => 'navigation'
  );
  $id = menu_link_save($arch_item);
  //gathering set mlids to cleanup nicely on reinstall 
  $mlids = variable_get('mmt_mlids');
  $mlids[] = $id; 
  variable_set('mmt_mlids', $mlids);

  foreach ($lines as $line) {
    $pair = explode(" ", $line);
    $name = $pair[0];
    $path = $pair[1];
    $nid = mmt_make_node($path, $name);
    mmt_save_path($nid, $path);
  }
}

//obosolete now, to be removed after done scavenging code from it
function old_mmt_load_nodes($pathsStr) {
  $lines = explode("\n", $pathsStr);
  $uri = array("mmt","archives");
  $plids_stack = array();
  $mlids = variable_get('mmt_mlids');
  $arch_item = array(
	  'link_path' => drupal_get_normal_path('mmt/archives'),
	  'link_title' => "Archives",
	  'menu_name' => 'navigation'
	);
  $id = menu_link_save($arch_item);
  $plids_stack[] = $id;
  $mlids[] = $id;
  foreach ($lines as $line) {
    if ($line == "") {
  	  array_pop($uri); //reset uri
      array_pop($plids_stack); //reset plids  	  
	} else {
	  $pair = explode(" ", $line);
	  $uri[] = $pair[0];
	  $nid = mmt_make_node($pair[1], $pair[0]); //$node->nid
    //path from url 
    $alias = $pair[1];  
    if (substr($alias, -1) == '/') {
      $alias = substr($alias, 0, -1);
    }
    $pathOpt = array(
		  'source' => 'node/' . $nid,
		  'alias' => $alias,
	  );
	  path_save($pathOpt);
    //link for tree menu

    $menuOpt = array (
		'link_path' => drupal_get_normal_path($alias),
        'link_title' => $uri[count($uri) - 1],
        'plid' => $plids_stack[count($plids_stack) - 1],
        'menu_name' => 'navigation',
	  );
    $id = menu_link_save($menuOpt);
	  drupal_set_message($alias);
	  $mlids[] = $id;
	  $plids_stack[] = $id;
  	}
  }
  variable_set('mmt_mlids', $mlids);
  menu_cache_clear_all();
}

/**
 * helper function for mmt_load_nodes, adds individual node
 */
function mmt_make_node($uri, $name) {

  $comps = explode('?', $uri);
  $dpath = $uri;
  if (count($comps) > 1) { //module
	  $node_type = 'mmt_module';
    $dpath = $comps[0] . "/" . $comps[1];

    $newnode = (object) array(
      'type' => $node_type,
      'uid' => 0,
      'created' => strtotime("now"),
      'changed' => strtotime("now"),
      'status' => 1,
	    'comment' => 2,
 	    'promote' => 0,
      'moderate' => 0,
      'sticky' => 0,
      'language' => 'und'  
    ); 
    $newnode->title = $name;
    $newnode->uri = $uri;
    node_object_prepare($newnode);//necessary ?
    node_save($newnode);
    return $newnode->nid;
 } else {
  return -1;
 }
}






