<?php

/*
 * Problems module
 */

function problems_mode_getSolutions($problem) {
  $query = db_query("SELECT * FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id
    INNER JOIN problem_has_solution phs ON phs.sid = n.nid
    WHERE phs.pid = :pid
    LIMIT 0,10
  ", array(':pid' => $problem->nid));
  $solutions = array();
  foreach ($query as $solution) {
    $solutions[] = $solution;
  }
  return $solutions;
}

function problems_view_getLinks($node) {
  $links = array(
      'solution-add' => l('Add a new Solution', 'node/add/solution/' . $node->nid),
      'similar-problem' => l('Add a similar Problem', 'node/add/problem')
  );
  return $links;
}

function problems_view_renderSolutions($problem){
  $solutions = problems_mode_getSolutions($problem);
  $return = array();
  foreach($solutions as $solution){
    $return[] = l($solution->title, 'node/'.$solution->nid);
  }
  $out = "<h3>Solutions</h3>";
  $out .= theme('item_list', array('items' => $return));
  return $out;
}

function problems_node_view($node){
  if($node->type == 'problem'){
    $node->content['solutions'] = array(
      '#markup' => problems_view_renderSolutions($node)
    );
  }
}
