<?php
// $Id: xdhtml_menu.module,v 1.50 2010/08/16 10:39:57 arancaytar Exp $


/**
 * @file xdhtml_menu.module
 * Initialization and various hook implementations.
 */

/**
 * Implementation of hook_help().
 */
function xdhtml_menu_help($path) {
  switch ($path) {
    case 'admin/config/user-interface/xdhtml_menu':
      $text = '<p>' . t('XDHTML Menu adds dynamic functionality to the menus of your site. Ordinarily, reaching the child elements below an item requires you to visit its page. With this module enabled, clicking on an item with child elements will expand it without leaving the page, saving you the time of waiting for the page to load.') . '</p>';
      $text .= '<p>' . t('<strong>Note:</strong> Links that gain a dynamic Javascript effect naturally stop working as normal links. Since you will still need to visit a page that has sub-items (like the <a href="@url">main administration page</a>), this module provides several different options for static and dynamic navigation to coexist.', array('@url' => url('admin'))) . '</p>';
      return $text;
  }
}

/**
 * Implementation of hook_init().
 * Adds CSS, Javascript and settings to the page.
 */
function xdhtml_menu_init() {
  module_load_include('inc', 'xdhtml_menu', 'xdhtml_menu.theme');
  drupal_add_css(drupal_get_path('module', 'xdhtml_menu') . '/xdhtml_menu.css');
  drupal_add_js(drupal_get_path('module', 'xdhtml_menu') . '/xdhtml_menu.js');
  drupal_add_js(array('xdhtmlMenu' => variable_get('xdhtml_menu_settings')), 'setting');
}

/**
 * Implementation of hook_menu().
 * Adds a settings page.
 */
function xdhtml_menu_menu() {
  $menu['admin/config/user-interface/xdhtml_menu'] = array(
    'title' => 'XDHTML Menu',
    'description' => 'Configure the behavior of XDHTML Menu.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xdhtml_menu_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'xdhtml_menu.admin.inc',
  );
  return $menu;
}

