<?php

function sharejsservices_init() {
  $settings['ShareJSConfig'] = array(
  	// this is all random data we're passing into the js object -- don't worry about it right now
  	'url' => variable_get('sharejs_base_url' , 'http://localhost:8000/')
  );
  drupal_add_js($settings, 'setting');
}

function sharejsservices_menu() {
	$items['localedit/sync/%node'] = array(
		    'page callback' => 'wysiwyg_etherpad_lite_setContent',
		    'access arguments' => array('access administration pages'),
		    'type' => MENU_NORMAL_ITEM,
		    'access callback' => array('node_access'),
	    	'access arguments' => array('update', 2),
	);
	$items["admin/config/content/etherpad-lite"] = array (
		'title' => 'ShareJS configurations',
    	'description' => 'Default configuration to be used by all ShareJSServices',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('sharejs_config_form'),
    	'access arguments' => array('access administration pages'),
    	'type' => MENU_NORMAL_ITEM,
	);
	$items['localedit/%node/%'] = array(
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('local_edit_form'),
	    'access callback' => array('node_access'),
	    'access arguments' => array('update', 1),
	    'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}

function sharejs_config_form($form, &$form_state) {
	$form["wel"] = array("#markup" => "<h2>Please adapt the ShareJS configurations</h2>");
	$form["sharejs_base_url"] = array(
		"#type" => "textfield",
		"#title" => "ShareJS URL",
    	'#default_value' =>   variable_get('sharejs_base_url' , 'http://localhost:8000/'),
	);
	$form["test"] = array(
			"#type" => "button",
		    '#default_value' => "Test",
			'#ajax' => array(
	      		'callback' => 'sharejs_test_connection',
	      		'wrapper' => 'result_div',
	),
	);
	$form['test_result'] = array(
	    '#prefix' => '<div id="result_div">',
	    '#suffix' => '</div>',
	);

	return system_settings_form($form);
}


function sharejs_test_connection($form, $form_state) {
	$values = $form_state["values"];
	$client = new EtherpadLiteClient($values["etherpad_api_key"], $values["etherpad_base_url"]."/api");
	$group = $client->createGroup();
	if ($group->groupID) {
		$form["test_result"]["#markup"] = "<h1 style='color:green'>Success!</h1>";
		$client->deleteGroup($group->groupID);
	}
	return $form["test_result"];
}

?>