<?php

function sharejsservices_init() {
  $settings['ShareJSConfig'] = array(
  	// this is all random data we're passing into the js object -- don't worry about it right now
  	'url' => variable_get('sharejs_base_url' , 'http://localhost:8000/')
  );
  drupal_add_js($settings, 'setting');
}

function sharejsservices_menu() {
	$items["admin/config/content/sharejs"] = array (
		'title' => 'ShareJS configurations',
    	'description' => 'Default configuration to be used by all ShareJSServices',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('sharejs_config_form'),
    	'access arguments' => array('access administration pages'),
    	'type' => MENU_NORMAL_ITEM,
	);

	$items["compile"] = array (
		'title' => 'Run filter over some text',
		'page callback' => 'editor_service_compile',
    	'access arguments' => array('access content'),
   	    'type' => MENU_CALLBACK,
	);
	return $items;
}

function editor_service_compile() {
	$text = $_POST["text"];
	$file = "smglo/source/dgraph.de.tex";
    global $filter_context;
    $filter_context = array();
    $info = mmt_get_path_info($file);

    $filter_context['mmt']['dpath'] = $info["dpath"];
   	global $filter_debug;
	$filter_debug = array();

    $markup = check_markup($text, "tex", "und");
    $output = array();

    if (isset($filter_debug["drutexml_latexml"])) {
    	$key = $filter_debug["drutexml_latexml"][1][0];
	   	$result = json_decode(_drutexml_cache_read($key."_r"));
	   	$log = $result->log;
	   	$matches = array();
	   	preg_match_all("|Error:[^\\n]*|", $log, $matches);

	   	$output["latexml"] = $matches[0];
    }

    foreach (array("mmt_compilation", "mmt_presentation") as $type) {
	    if (isset($filter_debug[$type])) {
    		$key = $filter_debug[$type][1][0];
		   	$result = json_decode(_drutexml_cache_read($key));
		   	$log = $result->log;
	   		$matches = array();
	   		preg_match_all("|Error:[^\\n]*|", $log, $matches);

		   	$output[$type] = $matches[0];
	    }
    }

	drupal_json_output($output);
}

function sharejs_config_form($form, &$form_state) {
	$form["wel"] = array("#markup" => "<h2>Please adapt the ShareJS configurations</h2>");
	$form["sharejs_base_url"] = array(
		"#type" => "textfield",
		"#title" => "ShareJS URL",
    	'#default_value' =>   variable_get('sharejs_base_url' , 'http://localhost:8000/'),
	);
	$form['test_result'] = array(
	    '#prefix' => '<div id="result_div">',
	    '#suffix' => '</div>',
	);

	return system_settings_form($form);
}


?>