<?php

/*
 * Problem module
 */

function problem_node_info() {
 return array(
	      'problem' => array(
				    'name' => "Problem",
				    'base' => 'node_content',
				    'description' => 'Exercises for learning purposes.',
				    'has_title' => '1',
				    'title_label' => 'Title',
				    'help' => '',
				    ));
}

/*
 *  This almost-empty hook is needed to list the content type?
 *  Well, that doesn't seem to be working here, though whatever we have going
 *  for corrections does actually seem to work, I think.
 */
function problem_form($node, &$form_state) {
  $form = array();
  return $form;
}

function problem_mode_getSolutions($problem) {
  $query = db_query("SELECT * FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id
    INNER JOIN problem_has_solution phs ON phs.sid = n.nid
    WHERE phs.pid = :pid
    LIMIT 0,10
  ", array(':pid' => $problem->nid));
  $solutions = array();
  foreach ($query as $solution) {
    $solutions[] = $solution;
  }
  return $solutions;
}

function problem_view_getLinks($node) {
  $links = array(
      'solution-add' => l('Add a new Solution', 'node/add/solution/' . $node->nid),
      'similar-problem' => l('Add a similar Problem', 'node/add/problem')
  );
  return $links;
}

function problem_view_renderSolutions($problem){
  $solutions = problem_mode_getSolutions($problem);
  $return = array();
  foreach($solutions as $solution){
    $return[] = l($solution->title, 'node/'.$solution->nid);
  }
  $out = "<h3>Solutions</h3>";
  $out .= theme('item_list', array('items' => $return));
  return $out;
}

function problem_node_view($node){
  if($node->type == 'problem'){
    $node->content['solutions'] = array(
      '#markup' => problem_view_renderSolutions($node)
    );
  }
}
