<?php

/*
 * PlanetMath OG Attach
 * This module takes care of attaching content to groups
 * This functionality should of course only be available for group members!
 */


function planetmath_og_attach_menu() {
  $items = array();

  // This particular path is more or less superseded by functionality from the
  // planetmath_attachable_content module
  $items['group/%/attach'] = array(
      'title' => 'Attach content',
      'type' => MENU_CALLBACK,
      'page callback' => 'planetmath_og_attach_content',
      'page arguments' => array(1),
      'access callback' => 'planetmath_og_attach_is_member',
      'access arguments' => array(1),
  );

  $items['group/confirm/%/%'] = array(
      'title' => 'Confirm attachment',
      'type' => MENU_CALLBACK,
      'page callback' => 'planetmath_og_attach_confirm',
      'page arguments' => array(2,3),//'nid_of_article','nid_of_problem'),
      'access arguments' => array('create correction content')
  );
  
  $items['group/decouple/%/%'] = array(
      'title' => 'Decouple content from the group connection',
      'type' => MENU_CALLBACK,
      'page callback' => 'planetmath_og_attach_decouple',
      'page arguments' => array(2,3),//'nid_of_article','nid_of_problem'),
      'access arguments' => array('create correction content'));   
  
  return $items;
}

function planetmath_og_attach_is_member($nid){
  global $user;
  //dd(planetmath_og_model_isUserMemberOfGroup($user->uid,node_load($nid)));
  return planetmath_og_model_isUserMemberOfGroup($user->uid,node_load($nid));
}

function planetmath_og_attach_content($nid){
  global $base_url;

  $count=db_query("SELECT COUNT(nid) as count FROM node WHERE type IN ('article', 'problem')")->fetchObject();

  if($count->count > 0) {
    $contents = planetmath_og_attach_get_all_content();
    $header = array(array('data' => 'Title', 'field' => 'n.nid'),
		    array('data' => "Type", 'field' => 'n.type'),
		    array('data' => "Author", 'field' => 'n.title'),
		    array('data' => 'Attach', 'field' => 'Attach')
		    );
    $rows = array();
    foreach ($contents as $item) {
      $rows[] = array(
		      array('data' => l($item->title, 'node/' . $item->nid), 
			                'field' => 'n.title'),
		      array('data' => l($item->type, 'node/' . $item->nid), 
			                'field' => 'n.type'),
		      array('data' => l(user_load($item->uid)->name, 
					'user/' . $item->uid), 'field' => 'n.author'),
		      array('data' => theme('attach_content_link',
					    array('url'=>$base_url
      						          . '/group/confirm/'
						          . $nid
                                                          . '/'
						          . $item->nid)))
		      );
    }
    return theme('table', array(
				  'header' => $header,
				  'rows' => $rows
				  )) 
           . theme('pager');
  } else {
    // Rather than spitting out the link and making a person click on it,
    // we should really just redirect to the relevant menu for "attach"...
    // return l('Add a new problem', 'node/add/problem');
    drupal_set_message("Add some content first.");
  }
}

function planetmath_og_attach_confirm($gid_of_group,$nid_of_content){
  global $user;

  $content_group = planetmath_og_model_getNodeEditingGroup($nid_of_content);
  $content_itself = node_load($nid_of_content);
  
  // You can only add something to a group (1) if you're in the group; AND (2) you're the
  // owner of the object you want to add; OR (3) you're in the editing group for the object
  // you want to add. 
  if(planetmath_og_model_isUserMemberOfGroup($user->uid,node_load($gid_of_group)) 
     && ( $user->uid == $content_itself->uid || 
	  (is_object($content_group) 
	   && planetmath_og_model_isUserMemberOfGroup($user->uid,$content_group)))) {
    og_membership_create('node',$gid_of_group,'node',$nid_of_content,'og_group_ref')->save();
    drupal_goto('node/'.$gid_of_group);
  } else {
    drupal_set_message("You don't have permission to edit <em>".l($content_itself->title,'node/'.$content_itself->nid)."</em>, so you can't add it to a group.");
    drupal_goto('attach/'.$gid_of_group);
  }
}

function planetmath_og_attach_decouple($gid_of_group,$nid_of_content){
    drupal_set_message('Node '.$nid_of_content.' is no longer attached to this group (needs to be implemented)');
    drupal_goto('node/'.$gid_of_group);
}

function planetmath_og_attach_get_all_content(){
  $db_or=db_or();
  $db_or->condition('n.type','article','=');
  $db_or->condition('n.type','problem','=');

  $query = db_select('node', 'n')
          ->fields('n')
          ->condition($db_or)
          ->extend('PagerDefault')
          ->extend('TableSort')
          ->limit(20);

  $result = $query->execute();
  return $result;
}


function theme_add_stuff($variables){
  //dd($variables);
  return l("Add Content", $variables['links']['target']);
}

function theme_attach_content_link($variables){
  $output = l(
	      t('Attach'),
	      $variables['url'],
	      array(
      
		    'attributes' => array(
					  'class' => "attach_planetmath_og_attach_icon",
					  'title' => t('Attach this content to group'),
					  ))
	      );
  return $output;
}

function planetmath_og_attach_theme($existing, $type, $theme, $path){
  return array('attach_content_link' => array(
				      'variables' => array('url' => NULL,
							   'query' => NULL)
				      ),
	       'add_stuff' => array(
				    'variables' => array('links' => array()),
				    )
  );
}

// Main point of entry is planetmath_attachable_content_node_view

