<?php

/*
 * Goal: building some "system stats" right into the "navigation menu"
 * (which will make it more navigation-like, though that still might
 * not be the best title).
 *
 * This needs to be broken down into several sub-modules.
 * 
 * Main problem to solve: Drupal doesn't like dynamic link text in menus!
 *
 * So if we want to adjust it, we have to create some sort of hack.
 * We use rely on planetmath_overview_links for some help.
 */

function planetmath_sysstats_menu() {
  $items = array();

  $items['sysstats'] = array(
      'title' => 'System Stats',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'planetmath_sysstats_show',
      'access arguments' => array('access content')
  );

  return $items;
}


function planetmath_sysstats_show(){

  $midnight = strtotime('midnight today');
  $yesterday = strtotime('midnight yesterday');
  $weekago = strtotime('previous week');
  $monthago = strtotime('previous month');
  $yearstart = strtotime('first day of January 2012');

  $html = '<table>';
  $html .= '<tr>';
  $html .= '<td>';
  $html .= '&nbsp;';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>messages</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>articles</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>users</b><sup>*</sup>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>corrections</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>p/s</b><sup>*</sup>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>q/a</b><sup>*</sup>';
  $html .= '</td>';
  $html .= '</tr>';


  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>total</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment")->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum'")->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article'")->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users")->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction'")->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem'")->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution'")->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question'")->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value <> NULL")->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>today</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment where created > :start", 
	   array(':start' => $midnight))->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users where created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question' and created > :start", 
		  array(':start' => $midnight))->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value > :start", 
		  array(':start' => $midnight))->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;
  $html .= '</td>';
  $html .= '</tr>';


  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>yesterday</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment where created > :start", 
	   array(':start' => $yesterday))->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users where created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question' and created > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value > :start", 
		  array(':start' => $yesterday))->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;
  $html .= '</td>';
  $html .= '</tr>';


  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>last week</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment where created > :start", 
	   array(':start' => $weekago))->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users where created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question' and created > :start", 
		  array(':start' => $weekago))->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value > :start", 
		  array(':start' => $weekago))->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;
  $html .= '</td>';
  $html .= '</tr>';


  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>last month</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment where created > :start", 
	   array(':start' => $monthago))->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users where created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question' and created > :start", 
		  array(':start' => $monthago))->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value > :start", 
		  array(':start' => $monthago))->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;

  $html .= '</td>';
  $html .= '</tr>';



  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>year to date</i>';
  $html .= '</td>';

  $comments = db_query("select COUNT(*) as count from comment where created > :start", 
	   array(':start' => $yearstart))->fetchObject();
  $ops = db_query("select COUNT(*) as count from node where type = 'forum' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $comments->count + $ops->count;
  $html .= '</td>';

  $art = db_query("select COUNT(*) as count from node where type = 'article' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $art->count;
  $html .= '</td>';

  $users = db_query("select COUNT(*) as count from users where created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $users->count;
  $html .= '</td>';

  $corrs = db_query("select COUNT(*) as count from node where type = 'correction' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $corrs->count;
  $html .= '</td>';

  $probs = db_query("select COUNT(*) as count from node where type = 'problem' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $solns = db_query("select COUNT(*) as count from node where type = 'solution' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $probs->count . '/' . $solns->count;
  $html .= '</td>';

  $qs = db_query("select COUNT(*) as count from node where type = 'question' and created > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $as = db_query("select COUNT(*) as count from node INNER JOIN field_data_field_question_closed fq ON node.nid = fq.entity_id WHERE type = 'question' and fq.field_question_closed_value > :start", 
		  array(':start' => $yearstart))->fetchObject();

  $html .= '<td>';
  $html .= $qs->count . '/' . $as->count;
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2011</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '533';  
  $html .= '</td>';
  $html .= '<td>';
  $html .= '92';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '181';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '51';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2010</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1462'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '151';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '504';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '107';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2009</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2459'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '529';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1976';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '274';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2008</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3620'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1114';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3345';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '944';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2007</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '4529'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1435';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3553';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2176';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2006</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3861';  
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1119';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3627';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3721';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2005</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3651'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '829';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3605';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1732';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2004</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2933'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1001';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3605';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2314';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2003</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1437'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '917';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2772';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1450';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2002</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '746';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1530';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1128';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1235';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2001</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '79';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '314';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '102';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '98';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '</table>';

  $html .= "Problems and solutions (p/s), and questions and answers (q/a) were
introduced in late 2012, when we switched to the new platform.  We
also took the opportunity to drop users who had never contributed.";
  
  if ($html) {
    return $html;
  } else {
    drupal_set_message("Um...?");
  }
}



