<?php
function advbooks_field_schema($field) {
  $columns = array(
    'counter_name' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
    'counter_parent' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
    'counter_formatter' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
  );
  $indexes = array(
    'counter_name' => array('counter_name'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}

?>