<?php


/**
 * implements hook_menu() - Called when loading the menu to create a new message
 */
function localized_discussions_menu() {
  $items = array();
  $items['post_local_discussion'] = array(
    'title' => 'Post Localized Discussion',
    'description' => 'Posts a Comment',
    'page callback' => 'localized_discussions_post_comment',
    // 'page callback' => 'localized_discussions_page',
    // 'access callback' => 'localized_discussions_check_post_comment',
    'access callback' => true,
  );

  return $items;
}


// function localized_discussions_menu() {
//   $items['hello'] = array(
//     'title' => 'Hello world!',
//     'page callback' => 'localized_discussions_page',
//     'access callback' => TRUE,
//   );

//   return $items;
// }

/**
 * Page callback for /hello.
 */
function localized_discussions_page() {
  return 'Hello world!';
}


function localized_discussions_post_comment() {

	$params = array(
		'title' => $_POST['title'],
		'body' => $_POST['body'],
		'xml_id' => $_POST['xml_id'],
		'node_id' => $_POST['node_id']
	);
  // dpm($params);
  print_r($params);

  global $user; // get user that is currently on the page
  $node = new stdClass();
  $node->title = $params['title'];
  $node->type = "local_discussion_question"; // or something along the lines of "node-question"
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE; 
  $node->uid = $user->uid;
  $node->status = 1; // (1 or 0): published or not
  $node->promote = 0; // (1 or 0): promoted to front page
  $node->comment = 2; // 0 = comments disabled, 1 = read only, 2 = read/write
  // Term reference (taxonomy) field
  $node->body[$node->language][0]['value'] = $params['body'];
  $node->xml_fragment_id[$node->language][0]['value'] = $params['xml_id'];
 
  $node->referenced_nid[$node->language][0]['value'] = $params['node_id'];

  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  print_r($node->nid);
  
  // dpm($user);
}


function localized_discussions_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'local_discussion_question') {
    // dpm($node); //to see node structure

    // Highlight the question
    // $$node->body[$node->language][0]['value']['#markup'] =  
    //   '<h2>' 
    //   // .  $node->body[$node->language][0]['value']
    //   .  '</h2>'

    // $node->content['']

    // Display the original link
    $node->content['body'][0]['#markup'] .= 
      '<i><p> The original article can be found <a href="?q=/node/' 
        . $node->referenced_nid[$node->language][0]['value'] 
        . '#'
        . $node->xml_fragment_id[$node->language][0]['value']
        . '">here</b></p></i>';
  // print_r($node);
  unset($node->content['xml_fragment_id']);
  unset($node->content['referenced_nid']);

  }

    // Change link reference

  /*
  $ref_node = node_load(ref_nid)
  $ref_body = $ref_node->body
  $fragment = ..look for fragment_id in body
  $node->content['xml_fragment_id'][0]['#markup'] = $fragment;
   */
}

function localized_discussions_check_post_comment() {
  global $user;
  if ($user->uid != 0) { // 0 is id of anonymous user
    return true;
  } else {
    return false;
  }
}

