<?php

/**
 * @file
 * Heartbeat defaults module file
 */

/**
 * Implements hook_views_api().
 */
function heartbeat_defaults_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function heartbeat_defaults_ctools_plugin_api($owner, $api) {
  if (($owner == 'heartbeat' && $api == 'heartbeat') || ($owner == 'ds' && $api == 'ds') || ($owner == 'ds_extras' && $api == 'ds_extras')) {
    return array('version' => 1);
  }
}