<?php
/*
 * @file
 *
 * Add a 'view source' tab to article pages for people who don't have
 * permission to edit.
 *
 * This can be achieved straightforwardly enough, with a menu that
 * provides the link, a suitable access control (show link on articles
 * iff the user has not got editing permission), and a function that
 * pulls out and minimally formats the source code listing.
 *
 * ENHANCEMENT: It would of course be nice to do some syntax
 * highlighting for the source code.
 */

function planetmath_view_source_menu() {
  $items = array();
  $items['node/%/source'] = array(
      'type' => MENU_LOCAL_TASK,
      'title' => 'Source',
      'page callback' => 'planetmath_view_source_show_listing',
      'page arguments' => array(1),
      'access callback' => 'planetmath_view_source_access',
      'access arguments' => array(1)
  );
  return $items;
}

/* We need to check whether the current user has edit permission for this node.
 * We only show the view source tab if they DO NOT have edit permission. 
 *
 * For users who do have edit permission, it would be ideal to give
 * access to the page, but still not see the TAB, but I guess that can
 * be sorted out later.
 */

function planetmath_view_source_access ($nid){
  global $user;  
  $node = node_load($nid);
  //TEMPORARY: for hacking purposes, we can show the link if they DO have access
  //  if (node_access('update', $node, $user))
  if (!node_access('update', $node, $user) 
      || (is_array($user->roles) && in_array('administrator', $user->roles)))
    {
      if ($node->type == 'article') {
	return TRUE;
      }
    }
  return FALSE;
}

function planetmath_view_source_show_listing($nid) {
  $page = "";
  $node = node_load($nid);
  //dpm($node);
  if (isset($node->field_latex)) {
    // actually it would be nice to pull in the preamble too
    $page .= '<pre style="white-space:pre-wrap;white-space: -moz-pre-wrap !important;white-space: -pre-wrap;white-space: -o-pre-wrap;width: 99%;">'
          . planetmath_view_source_build_short($node)
          . ' </pre>';
  }
  return $page;
}

function planetmath_view_source_build_short($node){
return '\documentclass{article}
'            . $node->field_latex['und'][0]['preamble']
             . "
\begin{document}
"
             . $node->field_latex['und'][0]['document'] 
             . "
\end{document}
";
}

function planetmath_view_source_build_full($node){
  //  dpm($node);
return '\documentclass{article}
\usepackage{xstring}
% Maintain a nice little history block to add things into
\edef\history{ }
\makeatletter
\newcommand{\historyAdd}[1]{\protected@edef\history{\history{}#1 }}
\makeatother
\newcommand{\historyAddEcho}[1]{#1\historyAdd{#1}}
% use these to build the actual "title" stuff
% (though, note, we could do a better job grabbing
% the "author" information out of Drupal)
\newcommand{\pmtitle}[1]{\title{{\bf #1}\footnote{\history}}}
\newcommand{\pmmodified}[1]{\date{{\it #1}}}
\newcommand{\pmmodifier}[2]{\author{{\it #1}\thanks{This text is available under the Creative Commons Attribution/Share-Alike License 3.0. You can reuse this document or portions thereof only if you do so under terms that are compatible with the CC-BY-SA license.}}}
% And this stuff will go into our little history thing, to display
% in the righthand margin
\def\pmcanonicalname#1{\historyAdd{$\langle${\it #1}$\rangle$\\ }}
\def\pmtype#1{\historyAdd{$\langle${\it #1}$\rangle$\\ }}
\def\pmprivacy#1{\historyAdd{Privacy setting: $\langle${\it #1}$\rangle$\\ }}
\def\pmclassification#1#2{\historyAdd{$\langle${\it #2}$\rangle$\\ }}
\def\pmcomment#1{\historyAdd{$\langle${\it #1}$\rangle$\\ }}
\def\pmcreated#1{\historyAdd{created: $\langle${\it \protect\StrGobbleRight{#1}{9}}$\rangle$\\  }}
\def\pmowner#1#2{\historyAdd{by: $\langle${\it #1}$\rangle$\\ }}
\def\pmrecord#1#2{\historyAdd{version: $\langle${\it #2}$\rangle$}}
\def\pmsynonym#1#2{}
\def\pmrelated#1{}
\def\pmdefines#1{}
\def\PMlinkname#1#2{\href{http://beta.planetmath.org/#2}{#1}}
\def\PMlinkescapeword#1{}
\def\PMlinkescapetext#1{#1}
\def\PMlinkexternal#1#2{\href{#2}{#1}}
\def\PMlinkid#1#2{\href{http://beta.planetmath.org/node/#2}{#1}}
%\pmauthor seems like a dumb command -- get rid of it.
%\def\pmauthor#1#2{\historyAdd{$\langle${\it #1}$\rangle$}}
\def\pmauthor#1#2{}
'
. $node->field_latex['und'][0]['preamble']
. '
\usepackage{hyperref}
\begin{document}
'
             . $node->field_latex['und'][0]['metadata']
             . "
\maketitle
"
             . $node->field_latex['und'][0]['document'] 
             . "
\end{document}
";
}

// EOF
