<?php

/**
 * Implements hook_menu
 * Adds entries for OAFF configuration and auto-loading nodes (from location set in config) 
 */
function oaff_menu() {
  $items = array();
  $items['admin/config/content/oaff'] = array(
    'title' => 'OAFF configuration',
    'description' => 'Configure OAFF',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oaff_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['oaff/autoload'] = array(
    'title' => "OAFF Init Nodes",
    'page callback' => 'oaff_create_nodes',
    'access callback' => 'oaff_setup_access',
    'menu_name' => 'navigation'
  );
  return $items;
}

/**
 * Implements access callback for OAFF auto-load feature
 * Only admin has access to reload mmt nodes
 */
function oaff_setup_access() {
  global $user;
  if ($user-> uid == 1) {//only admin has rights 
    return true;
  } else {
  return false;
  }
}

/**
 * Function to setup OAFF-specific functionality (CSS & JS) on page
 * OAFF-feature modules (e.g. MMT) define their own initialize methods 
 * to load further features (e.g. JOBAD modules)
 * Typically called from hook_node_view (i.e. for OAFF, oaff_node_view)
 */
function oaff_initialize() {
    libraries_load("jobad");
    // modules are loaded in specific oaff extensions (e.g. MMT)
    $inst_name = jobad_initialize();
    return $inst_name; 
}

/**
 * Implements hook_node_view
 * @param $node The node that is being assembled for rendering.
 * @param $view_mode The $view_mode parameter from node_view() (e.g. "full").
 * @param $langcode The language code used for rendering.
 */
function oaff_node_view($node, $view_mode, $langcode) {
  if ($view_mode != "full")
		return;
  global $filter_context;
  oaff_set_breadcrumb($node->nid);

  if ($node->type == 'glossary' || $node->type == 'mmtdoc') {
  	if (isset($filter_context['failed']) && $filter_context['failed']) { //time to report errors
       $source = $filter_context['source'];
       $pre = oaff_produce_preformatted($source);
       $output = oaff_mark_source_errors($pre, $filter_context['status']);
       $inst_id = oaff_initialize();

       $node->content['field_external'][0]['content']['#markup'] =  '<div id="' . $inst_id . '" class="bootstrap" >' . $output . '</div>'; 

       if (!oaff_has_error($node->nid)) { //must mark this as with error
        db_insert('oaff_errors') 
	      ->fields(array(
 		    'nid' => $node->nid,
 		    'type' => 2, //todo
		  ))->execute();
       }

    } else {
    	if (oaff_has_error($node->nid)) {// must mark this as fixed
          db_delete('oaff_errors')
  			->condition('nid', $node->nid)
  		    ->execute();
        }

	    $inst_id = oaff_initialize();

	    $result = db_query('SELECT e.field_lc_elid_value, t.field_lc_type_value, n.entity_id, node.title
	      FROM {field_data_field_lc_nid} n
	      INNER JOIN {field_data_field_lc_elid} e
	       ON n.entity_id = e.entity_id
	      INNER JOIN {field_data_field_lc_type} t
	        ON n.entity_id = t.entity_id
	      INNER JOIN {node}
	        ON n.entity_id = node.nid
	      WHERE n.field_lc_nid_value = :nid',
	      array(':nid' => $node->nid));

	    foreach ($result as $record) {
	        $nid = $record->entity_id;
	        $nid = str_replace("\r", '', $nid);
	        $nid = str_replace("\n", '', $nid);
	        $elid = $record->field_lc_elid_value; 
	        $elid = str_replace("\r", '', $elid);
	        $elid = str_replace("\n", '', $elid);
	        $type = $record->field_lc_type_value;
	        $type = str_replace("\r", '', $type);
	        $type = str_replace("\n", '', $type);
	        $title = $record->title;
	        $icon = $type;
	        if ($icon == "question") {
	          $icon = "warning"; //temporarily using this icon until question available in JOBAD
	        }
	        $options = array();
	        $options['class'] = $icon;
	        $options['text'] = $title;
	        $options['click'] = 'function() {window.open("?q=node/' . $nid . '");}';
	        if ($type == "question") {
	           $options['menu'] = '{"Answer" : function(){window.open("?q=node/' . $nid . '");}}';
	        }
	        if ($type == "error") {
	           $options['menu'] = '{"Fix" : function(){window.open("?q=node/' . $node->nid . '/edit", "_self");}}';
	        }

	        jobad_add_to_sidebar($inst_id, '$(document.getElementById("' . $elid . '"))', $options);
	    }

	    $content = $node->content['field_external'][0]['content']['#markup'];
	    $node->content['field_external'][0]['content']['#markup'] = '<div id="' . $inst_id . '" class="bootstrap" >' . $content . '</div>'; 
	}
  }
}

/**
 * function to check if an OAFF node has an error (during compilation)
 * @param $nid the id of the node that is being checked
 * @return true if node compilation has failed last time, false otherwise
 */
function oaff_has_error($nid) {
  $result =  $result = db_select('oaff_errors', 'e')
    ->fields('e')
    ->condition('nid', $nid,'=')
    ->execute()
    ->fetchAll();
  return (count($result) > 0);
}

/**
 * function to mark errors, annotates source string with error information
 * @param $source the source string
 * @param $status the compilation status (containing error information)
 * @return the processed string (with errors marked)
 */
function oaff_mark_source_errors($source, $status) {
  $color_catalog = array("Error" => "#FF8888", "Warning" => "#FFFF44", "Fatal" => "#FF3333","Info" => "#9999FF");
  foreach ($status as $filter_name => $filter_status) {
    foreach ($filter_status['messages'] as $msg) {
  	  $from_line = $msg['srcref']['from']['line'];
  	  $from_col = $msg['srcref']['from']['col'];
  	  $to_line = $msg['srcref']['to']['line'];
  	  $to_col = $msg['srcref']['to']['col'];

  	  $lines = explode("\n", $source);
  	  $before = substr($lines[$from_line], 0, $from_col -1);
  	  $after = substr($lines[$from_line], $from_col -1);
  	  $lines[$from_line] = $before . '<span style="background:' . $color_catalog[$msg['type']] .'" title="' . $msg['type'] . ': ' . $msg['shortMsg'] . '">' . $after;
  	  $before = substr($lines[$to_line], 0, $to_col -1);
  	  $after = substr($lines[$to_line], $to_col - 1);
  	  $lines[$to_line] = $before . '</span>' . $after;
  	  $source = join("\n", $lines);
  	}
  }
  return $source;
}

/**
 * Simple function to produce preformatted html element
 * just wraps a <pre> element around the text
 * @param $text the input text
 * @return the processed text
 */
function oaff_produce_preformatted($text) {
  return "<pre>" . check_plain($text) . "</pre>";
}

// ------------------------------- OAFF Autoload Crawler -------------------------------- \\
/**
 * Creates nodes for all documents in planetary_repo path where there is a oaff-connected content type 
 * associated with that format (based on file extension).  (All set up in OAFF configuration)
 */
function oaff_create_nodes() {
  _oaff_crawl_archives();
  return "Success";
}

/**
 * function crawl oaff archives for files to create nodes from (based on extension and OAFF config)
 * is called by oaff_create_nodes
 */
function _oaff_crawl_archives() {
  $res = planetary_repo_list("");
  foreach ($res as $file) {
    if (planetary_repo_is_dir($file) && $file[0] != '.') {
      _oaff_crawl_archive($file);
    }
  }
}

/**
 * function to crawl one archive for files to create oaff nodes from (based on extension and OAFF config)
 * is called by _oaff_crawl_archives() for each found archive
 * @param $path the VFS folder-path of the archive
 */
function _oaff_crawl_archive($path) { 
  $oaff_config = variable_get('oaff_config');
  $docbases = array();
  if (isset($oaff_config['docbases'])) {
    $docbases = $oaff_config['docbases'];
  }

  //getting info from manifest
  $mf_path = $path . "/META-INF/MANIFEST.MF";
  
  $manifest = planetary_repo_load_file($mf_path);
  $mf_lines = explode("\n",$manifest);
  $docbase = 'http://docs.omdoc.org/default'; //default
  $archive = 'default'; //default
  foreach ($mf_lines as $line) {
    $pair = explode(":", $line,2);
    if (trim($pair[0]) == "narration-base") {
      $docbase = trim($pair[1]);
    } elseif (trim($pair[0]) == "id") {
      $archive = trim($pair[1]);
    }
  }
  $docbases[$archive] = $docbase;
  $oaff_config['docbases'] = $docbases;
  variable_set('oaff_config', $oaff_config);
  //crawling source folder
  $nid = _oaff_crawl_source_folder($archive, $archive . "/source");
  oaff_set_children($oaff_config['archives_nid'], array($nid));
}

/**
 * function to crawl the source folder (where the source files are) of an archive for files 
 * to create oaff nodes from (based on extension and OAFF config)
 * @param $archive the name of the archive
 * @param $path the file path of the source folder
 */
function _oaff_crawl_source_folder($archive, $path) {
  $oaff_config = variable_get('oaff_config');
  $format = $oaff_config['formats'][$archive];
  $node_type = $oaff_config['node_types'][$format];
  $extension = $oaff_config['extensions'][$format];
  $docbase = $oaff_config['docbases'][$archive];
  
  $res = planetary_repo_list($path);
  $title = $path;
  if ($path == '') {
    $title = $archive;
  }
  $cids = array();
  $body = '';
  foreach ($res as $file) {
    $fpath = $path . "/" . $file;
    if ($path == '') {
      $fpath = $file;
    }
    if($file[0] != '.') {
      if (planetary_repo_is_dir($fpath)) {  
        $cids[] = _oaff_crawl_source_folder($archive, $fpath);
        $path_info = oaff_get_path_info($fpath);
        $dpath = $path_info['dpath'];
        $body .= '<p><a href="?q='. drupal_encode_path($dpath) .'">' . $file . "</a></p>\n";
      } else {
        $parts = explode('.', $file);
        $ext = $parts[count($parts) - 1];
        if ($ext == $extension) {
          $module = $parts[0];
          $lang = 'und'; //default
          if (count($parts) == 3) {
            $lang = $parts[1];
          }
          $path_info = oaff_get_path_info($fpath);
          $dpath = $path_info['dpath']; 

          $cids[] = oaff_create_node($module, $lang, $format, $dpath, $fpath, $node_type);        
          $body .= '<p><a href="?q='. drupal_encode_path($dpath) .'">' . $file . "</a></p>\n";
        }
      }
    }
  }
  $path_info = oaff_get_path_info($path);
  $menupath = $path_info['dpath'];  
  $nid = oaff_create_article($title, $body);
  oaff_set_children($nid, $cids);   
  oaff_save_path($nid, $menupath);
  return $nid;
}

/**
 * Explicitly save the parent-child relation of oaff nodes in the database (e.g. for building breadcrumb or menu later)
 * @param $pid the node id of the parent node
 * @param $cids the ids of the children 
 */
function oaff_set_children($pid, $cids) {
  foreach ($cids as $cid) {
    db_insert('oaff_node_parents')
      ->fields(array(
        'cid' => $cid,
        'pid' => $pid,
      ))
      ->execute();
  }
}

/**
 * function to set breadcrumb when viewing oaff nodes
 * adds, in order, links to OAFF ancestor nodes to the native drupal breadcrump
 * @param $nid the id of the node for which to construct breadcrumb
 */
function oaff_set_breadcrumb($nid) {
  $oaff_config = variable_get('oaff_config');
  $a_nid = $oaff_config['archives_nid'];

  $found_root = false;
  $pids = array();
  $pids[] = $nid; 
  while (!$found_root) {
    $result = db_select('oaff_node_parents', 'c')
      ->fields('c', array("pid"))
      ->condition('cid', $pids[count($pids) - 1],'=')
      ->execute()
      ->fetchAssoc();
    if (!isset($result['pid'])) {// not an oaff node
      return 0; // nothing to do
    }
    $pid = $result['pid'];
    $pids[] = $pid;
    if ($pid == $a_nid) {
      $found_root = true;
    }
  }
  $bc_entries = array();
  foreach ($pids as $pid) {
    $result = db_select('node', 'n')
      ->fields('n', array("title"))
      ->condition('nid', $pid,'=')
      ->execute()
      ->fetchAssoc();
    $path = drupal_get_path_alias('node/' . $pid);
    $title = $result['title'];
    $bc_entries[] =  '<a href="?q=' . $path . '">' . $title . '</a>';
  }
  $breadcrumb = drupal_get_breadcrumb();
  foreach ($breadcrumb as $entry) {
    $bc_entries[] = $entry;
  }
  $new_bc = array_reverse($bc_entries);
  drupal_set_breadcrumb($new_bc);
}

/**
 * create an oaff node, called by _oaff_crawl_source_folder 
 * @param $module the module name, becomes node title //TODO clarify document-module relation (e.g. for smglo)
 * @param $lang, the language of the node
 * @param $format the text format of the node
 * @param $dpath the document path (MMT URI) of the current document 
 * @param $location the physical location of the source file 
 * @param $node_type the type of the node to be created
 * @return the id of the newly created node
 */
function oaff_create_node($module, $lang, $format, $dpath, $location, $node_type) {
  $title = $module;
  $newnode = (object) array(
   'type' => $node_type,
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 2,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => $lang
  );

  $newnode->title = $title;
  $newnode->field_external['und']['0']['path'] = $location;
  $newnode->field_external['und']['0']['filter'] = $format;
  $newnode->field_external['und']['0']['dpath']['value'] = $dpath;

  node_object_prepare($newnode);//necessary ?
  node_save($newnode);
  return $newnode->nid;
}

/**
 * created an article node programmatically, (for OAFF documents corresponding to folders in source)
 * called from _oaff_crawl_source_folder
 * @param $title the title of the article (in principle, name of folder)
 * @param $body the body of the article (constructed based on its contents in _oaff_crawl_source_folder
 * @return the id of the newly created node
 */
function oaff_create_article($title, $body) {
  $newnode = (object) array(
   'type' => 'article',
   'uid' => 0,
   'created' => strtotime("now"),
   'changed' => strtotime("now"),
   'status' => 1,
   'comment' => 2,
   'promote' => 0,
   'moderate' => 0,
   'sticky' => 0,
   'language' => 'und'
  );
  $newnode->title = $title;
  $newnode->body['und'][0]['value'] = $body;
  $newnode->body['und'][0]['summary'] = $body;  
  $newnode->body['und'][0]['format'] = 'filtered_html';  

  node_object_prepare($newnode);//necessary ?
  node_save($newnode);
  return $newnode->nid;
}

// ############################# End OAFF Autoload Crawler ########################### \\

/**
 * implements hook_node_insert, creates an alias path for the node based on its document path (MMT URI) 
 * @param $node the node object to be inserted in the database
 */
function oaff_node_insert($node) {
  if ($node->type == 'glossary' || $node->type == 'mmtdoc') {
    $nid = $node->nid;
    $dpath = $node->field_external['und']['0']['dpath']['value'];
    oaff_save_path($nid, $dpath);
  }
}

/**
 * saves a path alias for a node, used by oaff_node_insert
 * @param $nid the node id
 * @param $path the alias to be saved (the MMT URI of the node)
 */ 
function oaff_save_path($nid, $path) {
  //saving path
  if (substr($path, -1) == '/') {
    $path = substr($path, 0, -1);
  }
  $pathOpt = array(
    'source' => 'node/' . $nid,
    'alias' => $path,
  );
  path_save($pathOpt);
}

/** 
 * api for MMT/VFS paths and locations, translated MMT URIs to physical location of source files 
 * @param $dpath the MMT URI
 * @return the physical location of the doc
 */
function oaff_get_location($dpath)  {
  $oaff_config = variable_get('oaff_config');
  $docbases = $oaff_config['docbases'];
  foreach ($docbases as $archive => $base) {
    if (strpos($dpath, $base) === 0) {
      $fragment = substr($dpath, strlen($base) + 1); //+1 removes the connecting slash as in 'base/fragment'
      return $archive . '/source/' . $fragment;
    }
  }
}

/**
 * builds information about a physical file location, including the archives it belongs in, filename, extension, etc
 * @param $location the file path 
 * @return an array with the path information
 */
function oaff_get_path_info($location) {
  $oaff_config = variable_get('oaff_config');
  $docbases = $oaff_config['docbases'];

  $lparts = explode('/', $location); //format is <archive-name>/source/<fragment path>
  $archive = $lparts[0];

  $filename = $lparts[count($lparts) - 1];
  $folderSegs = array_slice($lparts, 0, -1);
  $parent = join("/", $folderSegs);
  
  $fparts = explode('.', $filename);
  $extension = $fparts[count($fparts) - 1];
  
  $lang = 'und'; //default
  if (count($fparts) == 3) { //three file parts means <module>.<lang>.<ext>
    $lang = $fparts[1]; 
  }

  $modName = $fparts[0];

  //getting dpath  
  $relPathSegments = array_slice($lparts, 2);
  $relPath = "";//default for toplevel
  if (count($relPathSegments) != 0) {
    $relPath = join('/', $relPathSegments);
  }

  $rparts = explode('.', $relPath);

  if (count($rparts) > 1) { //there is an extension
    $rparts[count($rparts) - 1] = "omdoc"; 
  }
  $omdocRelPath = join(".", $rparts); 

  $dpath = $docbases[$archive] . '/' . $omdocRelPath;

  $path_info = array(
    'location' => $location,
    'archive' => $archive,
    'filename' => $filename,
    'extension' => $extension,
    'module' => $modName,
    'parent' => $parent, //parent folder
    'lang' => $lang,
    'dpath' => $dpath,
    );
  return $path_info;
}


// -------------------------- OAFF Configuration ------------------------- \\

/**
 * validation function of oaff configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 */
function oaff_config_validate($form, &$form_state) {
  $formats_S = $form_state['values']['oaff_archive_formats'];
  $formats_lines = explode("\n", $formats_S);
  foreach ($formats_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_archive_formats', t('Invalid line "' . $line .  '", must be space-separated pair of archive and text format'));
    }
  }

  $node_types_S = $form_state['values']['oaff_format_node_types'];
  $node_types_lines = explode("\n", $node_types_S);
  foreach ($node_types_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_format_node_types', t('Invalid line "' . $line .  '", must be space-separated pair of text format and nodetype'));
    }
  }
  
  $extensions_S = $form_state['values']['oaff_format_extensions'];
  $extensions_lines = explode("\n", $extensions_S);
  foreach ($extensions_lines as $line) {
    $pair = explode(' ', $line);
    if (count($pair) != 2) {
      form_set_error('oaff_format_extensions', t('Invalid line "' . $line .  '", must be space-separated pair of format and extension'));
    }
  }
}

/**
 * submit function of the oaff configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 */
function oaff_config_submit($form, &$form_state) {
  $formats_S = $form_state['values']['oaff_archive_formats'];
  $node_types_S = $form_state['values']['oaff_format_node_types'];
  $extensions_S = $form_state['values']['oaff_format_extensions'];
  
  oaff_config_set($formats_S, $node_types_S, $extensions_S);
}

/**
 * helper function to set oaff configuration, called by oaff_config_submit and oaff_install
 * @param $formats_S string encoding information of archive - format pairs
 * @param $node_types_S string encoding information of format - node_type pairs
 * @param $extensions_S string encoding information of format - (file) extension pairs
 */
function oaff_config_set($formats_S, $node_types_S, $extensions_S) {
  $formats_lines = explode("\n", $formats_S);
  $formats = array();
  foreach ($formats_lines as $line) {
    if (trim($line) != '') {
      $pair = explode(' ', $line);
      $formats[trim($pair[0])] = trim($pair[1]);
    }
  }

  $node_types_lines = explode("\n", $node_types_S);
  $node_types = array();
  foreach ($node_types_lines as $line) {
    if (trim($line) != '') {
      $pair = explode(' ', $line);
      $node_types[trim($pair[0])] = trim($pair[1]);
    }
  }

  $extensions_lines = explode("\n", $extensions_S);
  $extensions = array();
  foreach ($extensions_lines as $line) {
    if (trim($line) != '') {   
      $pair = explode(' ', $line);
      $extensions[trim($pair[0])] = trim($pair[1]);
    }
  }
  
  $oaff_config = variable_get('oaff_config');
  $oaff_config['formats'] = $formats;
  $oaff_config['node_types'] = $node_types;
  $oaff_config['extensions'] = $extensions;
  variable_set("oaff_config", $oaff_config);
}

/**
 * OAFF configuration form
 * @param $form the form to be validated
 * @param $form the form state, including filled in values
 * @return the newly built form
 */
function oaff_config_form($form, &$form_state) {
  $form['oaff_archive_formats'] = array(
    '#type' => 'textarea',
    '#title' => t('The Text Format associated with each archive'),
    '#default_value' => variable_get('oaff_archive_formats', ''),
    '#description' => t(' Archive name and its associated text format separated by space. One such pair per line'),
  );

  $form['oaff_format_node_types'] = array(
    '#type' => 'textarea',
    '#title' => t('The content type associated with each text format'),
    '#default_value' => variable_get('oaff_format_node_types', ''),
    '#description' => t('Text format and its associated node type separated by space. One such pair per line'),
  );

  $form['oaff_format_extensions'] = array(
    '#type' => 'textarea',
    '#title' => t('The extension associated with each format'),
    '#default_value' => variable_get('oaff_format_extensions', ''),
    '#description' => t('Text format and its associated extension separated by space. One such pair per line'),
  );

  $form['#validate'] = array('oaff_config_validate');
  $form['#submit'] = array('oaff_config_submit');

  return system_settings_form($form);
}
// ######################## End OAFF Configuration ######################### \\
