<?php

require_once( 'constants.php' );

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function tinfobar_help($path, $arg) {
  switch ($path) {
    case "admin/help#tinfobar":
      return '<p>'.  t("Creates an infobar for specific content types") .'</p>';
      break;
  }
}

/**
* Implements hook_preprocess_node
*
* Adds the infobar to the specific node types
*
* @param &$variables
*/
function tinfobar_preprocess_node(&$variables = '') {
   $node = $variables['node'];
   $acceptedTypes = array( 'article', 'lecture' );

   if (!empty($node) && in_array($node->type, $acceptedTypes) ) {
      drupal_add_css( drupal_get_path( 'module', 'tinfobar' ) . '/css/tIconMenu.css', array('weight'=>1) );
      drupal_add_css( drupal_get_path( 'module', 'tinfobar' ) . '/css/tTooltip.css', array('weight'=>1) );
      drupal_add_css( drupal_get_path( 'module', 'tinfobar' ) . '/css/MathML.css', array('weight'=>1) );
      drupal_add_css( drupal_get_path( 'module', 'tinfobar' ) . '/css/tInfoBar.css', array('weight'=>1) );
      drupal_add_js( drupal_get_path( 'module', 'tinfobar' ) . '/js/tIconMenu.js', array('weight'=>1)  );
      drupal_add_js( drupal_get_path( 'module', 'tinfobar' ) . '/js/tTooltip.js', array('weight'=>1)  );
      drupal_add_js( drupal_get_path( 'module', 'tinfobar' ) . '/js/tInfoBar.js', array('weight'=>2)  );
      drupal_add_js( drupal_get_path( 'module', 'tinfobar' ) . '/js/tInfoBar-config.js', array('weight'=>3) );
      
      global $user;
      echo '
      <div id="tInfoBar_info" style="display:none">
         <div id="info_username">'.$user->name.'</div>
         <div id="info_nodeType">'.$node->type.'</div>
         <div id="info_nodeId">'.$node->nid.'</div>
      </div>';
   }
}

/**
* Implements hook_menu
*/
function tinfobar_menu() {

   $items = array();
   $items['tInfoBar/getTokens'] = array(
      'title' => 'Return the tokens for the infobar for a specified context',
      'page callback' => '_tinfobar_getTokens',
      'access callback' => TRUE
   );
   $items['tInfoBar/add'] = array(
      'title' => 'Insert an item into the table',
      'page callback' => '_tinfobar_addItem',
      'access callback' => TRUE
   );
   $items['tInfoBar/get'] = array(
      'title' => 'Retrieve all items for a specified element',
      'page callback' => '_tinfobar_getItems',
      'access callback' => TRUE
   );
   
  return $items;
}

/**
* Retrieve all tokens for a specified context and of specific type
*
* @param $context
*     The context of the element
* @param $type = null
*     The type of the element
*/
function _tinfobar_getTokens( $context, $type = null ){
   $query = db_select( TABLE_TINFOBAR, 't' );
   $query->fields( 't' );
   
   $query->condition('t.context', $context);
   if( $type ) $query->condition('t.type', $type);
   
   $result = $query->execute();
   
   $a = array();
   foreach( $result as $r ) 
      if( !isset( $a[$r->wordid] ) )
         $a[$r->wordid] = array( $r->type => true );
      else
         $a[$r->wordid][$r->type] = true;
   
   $output = array();
   foreach( $a as $w => $v ){
      foreach( $v as $t => $p )
         $output[] = array( 'type' => $t, 'wordID' => $w );
   }
   
   return drupal_json_output( $output );
   exit;
}

/**
* Add an item to the database
*
* @param $type
*     The type of the item
* @param $id
*     The ID of the element
* @param $context
*     The context of the element
* @param $username
* @param $text
*     The Body of the comment
*/
function _tinfobar_addItem( $type, $id, $context, $username, $text ){
   db_insert( TABLE_TINFOBAR )
      ->fields(
         array(
            'type'      => $type,
            'wordID'    => $id,
            'context'   => $context,
            'user'      => $username,
            'text'      => $text
         )
      )->execute();

   return drupal_json_output( array( 'result' => 'true' ) );
}

/**
* Retrieve all items from the database for a specified element of a specified type in a specified context
*
* @param $type
*     The type of the item
* @param $id
*     The ID of the element
* @param $context = null
*     The context of the element
*/
function _tinfobar_getItems( $type, $id, $context = null ){
   $query = db_select( TABLE_TINFOBAR, 't' );
   $query->fields( 't' );
   
   if( $context ) 
      $query->condition('t.context', $context);
   $query->condition('t.type', $type);
   $query->condition('t.wordID', $id);
   
   $result = $query->execute();
   $a = array();
   foreach( $result as $r ) $a[] = $r;
   
   return drupal_json_output( $a );
   exit;
}
