<?php

function sally_menu() {
	$item["sally/search"] = array(
		"page callback" => "drupal_get_form",
		"page arguments" => array("sally_search_form"),
		"access callback" => true,
	);
	$item["sally/showdef"] = array(
		"page callback" => "sally_show_definition",
		"access callback" => true,
	);
	return $item;
}


function sally_show_definition($cd, $name) {
	$url = "https://tnt.kwarc.info/tntbase/stc/restful/jobad/basic?action=expandDefinition&cd=$cd&symbol=$name";
	echo getResult( $url, '', 'get', '' );
}


function sally_search_form($form, &$form_state) {
	$form["search"] = array(
		"#type" => "textfield",
		"#title" => "Search"
	);
	
	$form["filter"] = array(
			"#type" => "checkboxes",
			"#title" => "Filter options",
			"#options" => array("title", "title+body"),
	);
	
	$form["results"] = array(
			"#type" => "container",
	);

	$form["results"][0] = array(
			"#type" => "container",
	);
	
	
	return $form;
}

?>