<?php

function sally_menu() {
	$item["sally/search"] = array(
			"page callback" => "drupal_get_form",
			"page arguments" => array("sally_search_form"),
			"access callback" => true,
	);
	$item["sally/showdef"] = array(
			"page callback" => "sally_show_definition",
			"access callback" => true,
	);
	$item["sally/services/json"] = array(
			"page callback" => "sally_return_json",
			"access callback" => true,
	);
	$item["sally/semnav"] = array(
		"page callback" => "sally_show_graph",
		"access callback" => true,
	);

	
	return $item;
}

function sally_theme($existing, $type, $theme, $path) {
	return array(
			'sally_show_definition' => array(
					'variables' => array('content' => NULL),
					'template' => "sally_show_definition"
			),
			'sally_show_graph' => array(
					'variables' => array('content' => NULL),
					'template' => "sally_show_graph"
			),
			'sally_return_json' => array(
			)
			);
}
/*
 * Returns a page that gives the definition for the given ontology term.
 * $cd - the cd of the ontology term
 * $name - the name of the ontology term(symbol)
 * $token - token used for setting the context of the request
 */
function sally_show_definition($cd, $name, $token) {
	drupal_add_http_header('Content-Type', 'application/xhtml+xml; utf-8');
	$url = "https://tnt.kwarc.info/tntbase/stc/restful/jobad/basic?action=expandDefinition&cd=$cd&symbol=$name";
	$result = tntbase_get( $url );
	$sally = url("<front>", array("absolute"=>true)).drupal_get_path("module","sally");
	$jobad = url("<front>", array("absolute"=>true)).drupal_get_path("module","jobad");
	echo theme("sally_show_definition", array("content"=>$result, "jobad"=>$jobad, "sally"=>$sally, "token"=>$token));
}
/*
 * Returns a page that gives the dependency graph for the given ontology term.
 * $cd - the cd of the ontology term
 * $name - the name of the ontology term(symbol)
 * $token - token used for setting the context of the request
 */
function sally_show_graph($cd, $name, $token) {
	$url = "https://tnt.kwarc.info/tntbase/stc/BasicBrowser/vdocs/json-graph-termrefs.json?name=$cd&symbol=$name";
	$result = tntbase_get( $url );
	$jobad = url("<front>", array("absolute"=>true)).drupal_get_path("module","jobad");
	$sally = url("<front>", array("absolute"=>true)).drupal_get_path("module","sally");
	echo theme("sally_show_graph", array("content"=>$result, "jobad"=>$jobad, "sally"=>$sally, "token"=>$token));
}
/*
 * This is used to extend the dependency graph from a certain ontology term.
 *
 */
function sally_return_json($cd, $name){
	$url = "https://tnt.kwarc.info/tntbase/stc/BasicBrowser/vdocs/json-graph-termrefs.json?name=$cd&symbol=$name";
	$result = tntbase_get( $url );
	echo $result;
}

function sally_search_form($form, &$form_state) {
	$form["search"] = array(
			"#type" => "textfield",
			"#title" => "Search"
	);

	$form["filter"] = array(
			"#type" => "checkboxes",
			"#title" => "Filter options",
			"#options" => array("title", "title+body"),
	);

	$form["results"] = array(
			"#type" => "container",
	);

	$form["results"][0] = array(
			"#type" => "container",
	);


	return $form;
}

?>

