<?php

/*
 * An initial module for building some "system stats" right into the
 * "navigation menu" (which will make it more navigation-like, though
 * that still might not be the best title).
 * 
 * Problem to solve: Drupal doesn't like dynamic link text in menus!
 * So if we want to adjust it, we have to create some sort of hack.
 */

// See install function...

/* Implements hook_node_insert
 */
function planetmath_overview_node_insert ($node) {

  $users = db_query("SELECT COUNT(*) as count FROM users")->fetchObject();

  db_merge('menu_links')
    ->key(array('menu_name'=> 'navigation', 'link_path'=> 'people'))
    ->fields(array('link_title' => "Users: (" . $users->count . ")",
		   ))
    ->execute();

 $result = db_query("SELECT type, COUNT(*) as count FROM node GROUP BY type");

  foreach ($result as $obj) {
    db_merge('menu_links')
      ->key(array('menu_name'=> 'navigation', 'link_path'=> $obj->type . "s"))
      ->fields(array('link_title' => ucfirst($obj->type) . "s: (" . $obj->count . ")",
		   ))
      ->execute();
  }

  menu_cache_clear_all();
}

function planetmath_overview_menu() {
  $items = array();

  $items['sysstats'] = array(
      'title' => 'System Stats',
      'type' => MENU_CALLBACK,
      'page callback' => 'planetmath_overview_show',
      'page arguments' => array(1),
      'access arguments' => array('access comments')
  );

  return $items;
}

function planetmath_overview_show($nid){

  $html = '<table>';
  $html .= '<tr>';
  $html .= '<td>';
  $html .= '&nbsp;';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>messages</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>articles</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>users</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>corrections</b>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>p/s</b><sup>*</sup>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '<b>q/a</b><sup>*</sup>';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>total</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '26406';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '9133';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2824<sup>*</sup>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '14131';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>today</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>yesterday</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>last week</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>last month</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>year to date</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '223'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '153';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '56';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '31';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '<td>';
  $html .= 'xxx';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2011</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '533';  
  $html .= '</td>';
  $html .= '<td>';
  $html .= '92';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '181';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '51';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2010</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1462'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '151';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '504';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '107';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2009</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2459'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '529';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1976';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '274';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2008</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3620'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1114';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3345';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '944';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2007</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '4529'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1435';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3553';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2176';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2006</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3861';  
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1119';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3627';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3721';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2005</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3651'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '829';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3605';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1732';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2004</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2933'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1001';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '3605';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2314';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2003</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1437'; 
  $html .= '</td>';
  $html .= '<td>';
  $html .= '917';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '2772';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1450';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2002</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '746';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1530';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1128';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '1235';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '<tr>';
  $html .= '<td>';
  $html .= '<i>2001</i>';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '79';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '314';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '102';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '98';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '<td>';
  $html .= '--';
  $html .= '</td>';
  $html .= '</tr>';

  $html .= '</table>';

  $html .= "Problems and solutions (p/s), and questions and answers (q/a) were
introduced in late 2012, when we switched to the new platform.  We
also took the opportunity to drop users who had never contributed.";
  
  if ($html) {
    return $html;
  } else {
    drupal_set_message("Um...?");
  }
}


