<?php
// based loosely on og_ui_add_users from og_ui.admin.inc

// In order to hook up this action, we need
// (1) - menu
// (2) - form
// (3) - do something with the value from the form via the submit hook

function planetmath_owner_menu() {
  $items = array();

  $items['node/%/transfer'] = array(
    'page callback' => 'drupal_get_form',
    'title' => 'Transfer ownership',
    'page arguments' => array('planetmath_owner_transfer', 1),
    'type' => MENU_NORMAL_ITEM,
    'file' => "planetmath_owner.module",
    'weight' => 5,
    // We need to change this so that only the owner has permission to do this
    'access callback' => 'planetmath_owner_rights',
    'access arguments' => array(1),
  );

  return $items;
}

function planetmath_owner_rights ($nid) {
  global $user;
  $node = node_load($nid);
  if ($user->uid == $node->uid) {
    dd("User has owner rights");
    return TRUE;
  } else {
    dd("User does not have owner rights");
    return FALSE;
  }
}

function planetmath_owner_transfer($form, &$form_state, $nid) {
  // if we wanted to add a breadcrumb here that would be cool

  // Do some stuff to get the name of the thing we're working with
  $node = node_load($nid);
  $title = $node->title;

  $form['nid'] = array('#type' => 'value', '#value' => $nid);

  $form['planetmath_newowner'] = array(
    '#type' => 'fieldset',
    '#title' => t('Transfer %title', array('%title' => $title)),
  );
  $form['planetmath_newowner']['name'] = array(
    '#type' => 'textfield',
    '#title' => t('User name'),
    '#autocomplete_path' => 'user/autocomplete',
    '#required' => TRUE,
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Transfer'));

  return $form;
}

function planetmath_owner_transfer_validate($form, &$form_state) {
}

function planetmath_owner_transfer_submit($form, &$form_state) {
  $nid = $form_state['values']['nid'];
  // I don't know if we have to do anything with this
  //  $state = $form_state['values']['state'];

  $node = node_load($nid);
  $account = user_load_by_name($form_state['values']['name']);


  $node->uid = $account->uid;
  node_save($node);
  drupal_goto("node/".$node->nid);

  drupal_set_message(t('%type transfered to %user.', 
		       array('%type' => $node->type,
			     '%user' => format_username($account))));

}