<?php

/**
 * Adds useful features for the organic groups
 * @author Alex Dumitru <m.dumitru@jacobs-university.de> 
 *
 * Ported to og-7.x-2.x-dev by Joe Corneli <holtzermann17@gmail.com>
 * and Lucas Anastasiou <holtzermann17@gmail.com>
 */

/*
 * NOTES:
 * Instead of doing db_insert
 * Maybe we should be using
 *  og_membership_save(og_membership_create($group->nid, 'user', $uid->userid));
 * and
 *  og_membership_save(og_membership_create($group->nid, 'node', $nid->objectid));
 * ...
 * But testing is still needed to see whether those functions work at all!  If
 * they work, then they are at a higher level of abstraction than database calls
 * and that is likely better for portability.
 */

define("PLANETMATH_OG_COAUTHOR_GROUP_PREFIX", "Editing Group for ");
define("PLANETMATH_OG_WW_GID", 1);

// use this to limit the places where you can create a group
define("PLANETMATH_OG_ACCEPTED_CONTENT_TYPES", serialize(array('article')));

function planetmath_og_model_getNodeEditingGroup($nid) {
  // This query will select ONE group from the og_membership table
  // that contains this node.  But we actually don't want that.
  $result = db_query("SELECT om.etid as myid, om.gid as mygid
    FROM og_membership om INNER JOIN field_data_field_group_subtype subtype
    WHERE om.entity_type = 'node' AND om.etid = :etid
    AND subtype.field_group_subtype_value = 'Coauthors'
    AND subtype.entity_id = om.gid ", array('etid' => $nid))
      ->fetchObject();

  if (isset($result->myid)) {
    $group = node_load($result->mygid);
  } else {
    $group = false;
  }
  return $group;
}

function planetmath_og_model_getCoauthors ($nid) {

  $coauthors = array();
  $group=planetmath_og_model_getNodeEditingGroup($nid);

  if($group){

    $results = db_query("SELECT users.name,users.uid FROM og_membership om INNER JOIN users ON om.etid = users.uid WHERE om.entity_type = 'user' AND om.gid= :gid", array(':gid' => $group->nid));

    foreach ($results as $result) {
      $coauthors[] = $result;
    }
  }
  return $coauthors;
}

function planetmath_og_model_getWWGroup() {
  return PLANETMATH_OG_WW_GID;
}

function planetmath_og_model_isUserGroupAdmin($uid, $group) {
  $isAdmin = false;
  if ($group->uid == $uid) {
    $isAdmin = true;
  } else {
    $countAdmin = db_query("SELECT COUNT(uid) AS count_uid FROM og_users_roles WHERE rid = 3 AND uid = :uid AND gid = :gid", array(':uid' => $uid, ':gid' => $group->nid))->fetchObject()->count_uid;
    if ($countAdmin >= 1) {
      $isAdmin = true;
    }
  }
  return $isAdmin;
}

// A PENDING user will still exist in the database, but not with a state=1
// So we use this fact to discriminate between "members" and "nonmembers".
function planetmath_og_model_isUserMemberOfGroup($uid, $group) {
  $isMember = false;
  if ($group->uid == $uid) {
    $isMember = true;
  } else {
    $countMembership = db_query("SELECT COUNT(etid) AS count_uid FROM og_membership WHERE gid = :gid AND etid = :uid AND entity_type = 'user' AND state = 1", array(':uid' => $uid, ':gid' => $group->nid))->fetchObject()->count_uid;
    if ($countMembership >= 1) {
      $isMember = true;
    }
  }
  return $isMember;
}

// If we're going to use 7.x-2.x-dev then this 
function planetmath_og_model_insertNodeEditingGroup($node) {
  $groupTitle = PLANETMATH_OG_COAUTHOR_GROUP_PREFIX . $node->title;

  $groupNode = (object) array(
              'type' => 'group',
              'title' => $groupTitle,
              'uid' => $node->uid,
              'status' => 1,
              'comment' => 1,
              'changed' => REQUEST_TIME,
              'created' => REQUEST_TIME,
              'language' => LANGUAGE_NONE
  );
  $groupNode->field_group_subtype['und'][0]['value'] = 'Coauthors';
  node_save($groupNode);

  /* $gid = db_insert('og')->fields(array( */
  /*             'etid' => $groupNode->nid, */
  /*             'entity_type' => 'node', */
  /*             'label' => $groupNode->title, */
  /*             'state' => 1, */
  /*             'created' => REQUEST_TIME */
  /*         ))->execute(); */

  db_insert('og_membership')->fields(array(
      'type' => 'og_membership_type_default',
      'etid' => $node->nid,
      'entity_type' => 'node',
      'gid' => $groupNode->nid,
      'group_type' => 'node',
      'state' => 1,
      'created' => REQUEST_TIME,
      'field_name' => 'og_group_ref',
      'language' => 'en'
  ))->execute();
  return $groupNode->nid;
}

function planetmath_og_model_addUserToGroup($gid, $uid, $isAdmin = false) {
  db_insert('og_membership')->fields(array(
      'type' => 'og_membership_type_default',
      'etid' => $uid,
      'entity_type' => 'user',
      'gid' => $gid,
      // THIS NEXT LINE IS IMPORTANT FOR THE 7.x-2.x-dev VERSION OF OG! 
      'group_type' => 'node',
      'state' => 1,
      'created' => REQUEST_TIME,
      // THIS NEXT LINE IS IMPORTANT FOR THE 7.x-2.x-dev VERSION OF OG! 
      'field_name' => 'og_user_group_ref',
      'language' => 'en'
  ))->execute();

  db_insert('og_users_roles')->fields(array(
      'uid' => $uid,
      'rid' => $isAdmin ? 3 : 2,
      'gid' => $gid
  ))->execute();
}

function planetmath_og_model_addContentToGroup($gid, $nid) {
  db_insert('og_membership')->fields(array(
      'type' => 'og_membership_type_default',
      'etid' => $nid,
      'entity_type' => 'node',
      'gid' => $gid,
      // THIS NEXT LINE IS IMPORTANT FOR THE 7.x-2.x-dev VERSION OF OG! 
      'group_type' => 'node',
      'state' => 1,
      'created' => REQUEST_TIME,
      // THIS NEXT LINE IS IMPORTANT FOR THE 7.x-2.x-dev VERSION OF OG! 
      'field_name' => 'og_group_ref',
      'language' => 'en'
  ))->execute();
}

// We should extend this with the ability to create an arbitrary group
function planetmath_og_menu() {
  $items = array();
  $items['node/%/pmgroup'] = array(
      'type' => MENU_LOCAL_TASK,
      'title' => 'Coauthors',
      'page callback' => 'planetmath_og_view_coAuthorsPage',
      'page arguments' => array(1),
      'access callback' => 'planetmath_og_access_coAuthorsPage',
      // argument to this callback duh
      'access arguments' => array(1)
  );

  $items['planetmath_og/create-coauth-group/%'] = array(
      'type' => MENU_CALLBACK,
      'title' => 'Create CoAuthor Group',
      'page callback' => 'planetmath_og_callback_createCoAuthGroup',
      'page arguments' => array(2),
      'access arguments' => array('create group content')
  );  
  
  
  
  return $items;
}

// Called for every node view!  But filters out everything besides articles (for now)
function planetmath_og_access_coAuthorsPage($nid){
  $node = node_load($nid);
  if(in_array($node->type, unserialize(PLANETMATH_OG_ACCEPTED_CONTENT_TYPES))){
    return true;
  }
  return false;
}

// user = 3
// article = 12
function planetmath_og_view_coAuthorsPage($nid) {
  $node = node_load($nid);
  $group = planetmath_og_model_getNodeEditingGroup($node->nid);
  $page = "";
  global $user;

  if ($group === false) {
    if ($node->uid == $user->uid) {
      $page = planetmath_og_view_coAuthorsNoGroupPage($node);
    }
    else{
      $page = "No co-author group was created yet. This can only be done by the original author.";
    }
  } else {
    if (planetmath_og_model_isUserGroupAdmin($user->uid, $group)) {
      $page = planetmath_og_view_coAuthorsGroupPage($group,$nid);
    } else {
      $page = planetmath_og_view_requestInvitePage($node, $group);
    }
  }
  return $page;
}

///*
// * a helper function to reverse find the article (node in general) id 
// * from the corresponding coauthor group id
// */
//function get_node_id_from_editing_group_id($gid){
//  $result = db_query("SELECT  ".
//      " = :nid ", array(':gid' => $gid));
//  return $result->nid;
//}

// http://metameso.org/p/group/node/13/admin/people/add-user
function planetmath_og_view_coAuthorsGroupPage($group,$nid) {
  $links = array( 
      'transfer-ownership' => l("Transfer ownership", 'node/'.$nid.'/transfer'),
      'add-people' => l("Add co-authors", 'group/node/' . $group->nid . '/admin/people/add-user'),
      'people' => l('Manage co-authors', 'group/node/' . $group->nid . '/admin/people')
  );
  return theme('item_list', array('items' => array_values($links), 'type' => 'ul', 'options' => array()));
}

function planetmath_og_view_coAuthorsNoGroupPage($node) {
  $html = "<p>Currently, there is no co-author group associated to this one.</p>" .
          "<p>".l("Transfer ownership","node/".$node->nid."/transfer")."</p>".
          "<p>".l("Create co-author group", 'planetmath_og/create-coauth-group/' . $node->nid)."</p>";
  return $html;
}

function planetmath_og_callback_createCoAuthGroup($nid) {
  $node = node_load($nid);
  if ($node->nid) {
    $gid = planetmath_og_model_insertNodeEditingGroup($node);
    if ($gid) {
      drupal_set_message("The co-author group was successfully created");
    } else {
      drupal_set_message("There was an error creating the co-author group", "error");
    }
  } else {
    drupal_set_message("The group was not created because the article supplied does not exist", "error");
  }
  drupal_goto('node/' . $nid . '/pmgroup');
}


function planetmath_og_view_requestInvitePage($node, $group) {
  global $user;
  $html = "";
  if (!planetmath_og_model_isUserMemberOfGroup($user->uid, $group)) {
    $html = l("Request to join as a co-author", 'group/node/' . $group->nid . '/subscribe');
  } else {
    $html = "You are a co-author on this article.";
  }
  return $html;
}

/*
 * Implements hook_user_insert
 */

// This hook will make it so that every new user is added to the world writable group.

function planetmath_og_user_insert($edit, $account, $category) {
  $gid = planetmath_og_model_getWWGroup();
  planetmath_og_model_addUserToGroup($gid, $account->uid);
}

// We need to be able to add groups, and we need to be able to add nodes as a subroutine.
// Returns the nid of the new node
function planetmath_og_node_add_programmatic($type, $title, $uid, $body_text, $group_subtype=NULL) {

  $node = (object) array("type"=>$type, "title"=>$title, "language"=>LANGUAGE_NONE);
  node_object_prepare($node);
  $node->uid = $uid;
  $node->body[$node->language][0]['value']   = $body_text;
  $node->body[$node->language][0]['summary'] = text_summary($body_text);
  $node->body[$node->language][0]['format']  = 'tex_editor';

  if ($group_subtype) {
    $node->field_group_subtype[$node->language][0]['value'] = $group_subtype;
  }
 
  node_save($node); // After this call we'll get a nid
  return $node->nid;
}

// We need to be able to add groups, and we need to be able to add nodes as a subroutine.
// The default subtype is "Team".
// You can also add groups w/ subtype "Coauthors" or "Buddies".

function planetmath_og_group_add_programmatic($name,$userid,$description,$group_subtype='Team') {
  $etid = planetmath_og_node_add_programmatic('group', $name, $userid, $description, $group_subtype);
  // ANOTHER DIFFERENCE FROM OLD VERSION OF THIS CODE
  return entity_load_single('node', $etid);
}

// MODIFY THE DISPLAY OF GROUPS USING A THEME

function planetmath_og_theme($existing, $type, $theme, $path) {
  $to_return = array(
	       'planetmath_group_users' => array(
						 'variables' => array('links' => array()),
						 ),
	       'planetmath_group_content' => array(
						   'variables' => array('links' => array()),
						   ),
	       );
  return $to_return;
}

// shall we pass in an extra variable as a "see more" field?
function theme_planetmath_group_users($variables) {
  $return = "Members: ";
  foreach ($variables['links'] as $link) {
    $return = $return . l($link->name, 'user/' . $link->uid) . " ";
    }
  return $return;
}

function theme_planetmath_group_content($variables) {
 $return = "Content: ";
 foreach ($variables['links'] as $link) {
   $return = $return . l($link->title, 'node/' . $link->nid) . " ";
   }
 return $return;
}

function planetmath_og_node_view($node) {

 if($node->type == 'group'){ 

  // first select relevant information about group members (given an nid)
  // this can be made into a separate function

    $user_info = db_query("SELECT u.name, u.uid FROM users u INNER JOIN og_membership ON og_membership.etid = u.uid WHERE og_membership.gid = :nid AND og_membership.group_type='node' AND og_membership.entity_type = 'user' AND og_membership.state = 1 ORDER BY u.access LIMIT 20;", array(':nid' => $node->nid));

    // It might be interesting to do a count of the number of users, and only include a link to the full roster if there are more than 20, but I think I found a cheaper solution

    $links = array();
    foreach ($user_info as $result) {
      $links[] = $result;
    }
   
    $node->content['planetmath_group_users'] = array(
        '#markup' => '',
        '#weight' => 10,
        '#theme' => 'planetmath_group_users',
        '#links' => $links,
    );
    
    // then select relevant information about group content (nodes) 
    // maybe we also want this as a separate function

    $content_info = db_query("SELECT n.title,n.nid FROM node n INNER JOIN og_membership WHERE og_membership.gid =:nid AND og_membership.entity_type='node' AND og_membership.entity_type = 'node' AND og_membership.etid = n.nid ORDER BY n.changed LIMIT 20", array(':nid' => $node->nid));

   $links = array();
   foreach ($content_info as $result) {
     $links[] = $result;
   }
   
   $node->content['planetmath_group_content'] = array(
       '#markup' => '',
       '#weight' => 10,
       '#theme' => 'planetmath_group_content',
       '#links' => $links,
   );

  }

}

/**
 * Implementation of hook_form_FORM_ID_alter()
 * @param array $form
 * @param array $form_state
 * @param array $form_id 
 *
 * The purpose of this code is to adjust the form that the user is
 * presented with when editing an article, so that the "buddies list"
 * of the user is presented as the default "team" to share this article
 * with (and so that only groups that are "teams" are available as options)
 *
 * NOTE: We should double check the logic given that the latest 
 * understanding of different types of groups might be different
 * from what it was when this function was written.
 * 
 * COMMENT: This implementation may be inefficient, since we use
 * node_load()... but it does work.
 *
 * NOTE: Some later implementation would be needed to make groups show
 * up as an option to add content directly when they are not an admin (if
 * we want that).
 */

function planetmath_og_form_article_node_form_alter(&$form, &$form_state, $form_id) {
  
  global $user;
  $filtered_group_list = array();

  // we'll switch the presentation to checkboxes... the dropdown list 
  // is annoying to work with.  This list could also be annoying to work
  // with, but it's a start to something better.

  //dpm($form['og_group_ref']);

  $form['og_group_ref']['und'][0]['default']['#type'] = 'checkboxes';

  $form['og_group_ref']['und'][0]['admin']['#access'] =FALSE;

  /* This doesn't work right, but it's a sorta nice idea... see
     planetmath_og_disable_element for details.  The idea is from here:
     http://drupal.stackexchange.com/questions/832/how-can-i-disable-a-single-checkbox-in-a-checkboxes-fapi-element */

  //   $form['og_group_ref']['und']['#process'][] = 'planetmath_og_disable_element';

  // find the 'buddy' group of this user (if one exists)
  // TODO: need to sort things out so that the value is set properly, otherwise
  // there are problems when trying to save the article

  // dd($form['og_group_ref']);

  $buddy_group_id = planetmath_og_get_user_buddy_group_id($user->uid);

  // set the buddy group as one of the default values
  // NOTE: we could be more sophisticated about this, and only *add* it as
  // a default value when the article is new.
  if (!is_null($buddy_group_id)){
    $form['og_group_ref']['und'][0]['default']['#default_value'][] = $buddy_group_id;
  }

  // We will filter out all irrelevant options.
  // Specifically: we preserve the "none" option...
  $filtered_group_list['_none']="- None -";

  if(isset($form['og_group_ref']['und'][0]['default']['#options'])) {
    foreach ($form['og_group_ref']['und'][0]['default']['#options'] as $gid=>$group_title){
      $group = node_load($gid);
      // ... and all Teams (that they are only presented here b/c the user is a member)
      if (isset($group->field_group_subtype['und'][0]) && 
	  $group->field_group_subtype['und'][0]['value'] == 'Team' ||
	  // ... and we preserve anything that was marked as a "default value" already
	  // which, in particular, includes anything that the item aleady belongs to
	  in_array($gid, $form['og_group_ref']['und'][0]['default']['#default_value'] )){
	$filtered_group_list[$gid]=$group_title;
      }
    }
  }

  // Note that selecting "none" AND something else just causes the other
  // things to be preserved
  $form['og_group_ref']['und']['#options'] = $filtered_group_list;
}

// This didn't work, but actually it would be more
// interesting to completely *hide* any options that we're not interested in showing
// using a rewritten version of form_process_checkboxes
// see http://api.drupal.org/api/drupal/includes!form.inc/function/form_process_checkboxes/7

function planetmath_og_disable_element($element) {
  foreach (element_children($element) as $key) {
    if ($key == '1') {
      $element[$key]['#disabled'] = TRUE;
      return;
    }
  }
}

function printr($data, $exit = TRUE) {
  if ($data) {
    print '<pre>';
    print_r($data);
    print '</pre>';
  }
  if ($exit) {
    exit;
  }
}

// TODO: This needs to be implemented properly.
function planetmath_og_get_user_buddy_group_id($uid){
  $gid = NULL;
  $user = user_load($uid);
  if(isset($user->buddy_list) && !empty($user->buddy_list)){
    //$gid=$user->buddy_list['und'][0]['value'];
    $gid=$user->buddy_list['und'][0]['nid'];
  }
  return $gid;
}

/* implements hook_form_FORM_ID_alter
 */

function planetmath_og_form_group_node_form_alter(&$form, &$form_state, $form_id) {
  //dd($form);
  // This gets rid of some "options" that are actually confusing (particularly since the user
  // would have been supposed to choose the default anyway)
  $form['field_group_subtype']['#access'] = FALSE;
  $form['group_group']['#access'] = FALSE;
  $form['og_views']['#access'] = FALSE;
}

/* implements hook_form_FORM_ID_alter
 */

function planetmath_og_form_og_ui_add_users_alter(&$form, &$form_state, $form_id) {
  //dpm($form);
  $form['og_user']['state']['#access'] = FALSE;
  $form['og_user']['state']['#default_value'] = OG_STATE_ACTIVE;
  $form['og_user']['field_name']['#access'] = FALSE;
  $form['membership_fields']['og_membership_request']['und'][0]['value']['#description'] = "Send a note to the new group member (optional).";
  //dd($form);
}
