<?php
function advanced_books_field_schema($field) {
  $fields = array(
    'counter_name' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
    'counter_parent' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
    'counter_formatter' => array('type' => 'varchar', 'length' => 255, 'not null' => FALSE),
  );
  return array(
    'columns' => $fields,
    'primary key' => array("counter_name"),
  );
}

?>