<?php

	$WebSMLUrl = 'http://ruby.eecs.jacobs-university.de:8080/'; //url of websml; including port
	$WebSMLRPCUser = 'rpc'; //WebSML option accessData.rpc.username
	$WebSMLRPCPass = 'pleasechange'; //WebSML option accessData.rpc.password

	function WebSMLJSON($server_url, $user, $pass, $method, $args){
		/* makes a request to a WebSML server.
			$server_url: URL of the WebSML Server excluding the path ro rpc, for example: 'http://localhost:8080/'
			$user: Rpc username, for example 'rpc'
			$pass: RPC password, for example 'pleasechange'
			$method: name of method to call, for example 'test.echo'
			$args: Array of arguments, for example array('hello', 'world');

			MOST code from http://ptrofimov.wordpress.com/2011/04/27/php-class-to-implement-json-rpc-2-0-protocol/
		*/

		$request = new stdClass();
		$request->jsonrpc = '2.0';
		$request->method = $method;
		$request->params = $args;
		$request->id = md5( uniqid( microtime( true ), true ) );
		$request_json = json_encode( $request );
		$ch = curl_init();
		curl_setopt_array($ch, array(
			CURLOPT_URL => $server_url.'/rpc', 
			CURLOPT_POST => 1,
			CURLOPT_POSTFIELDS => $request_json, 
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_HTTPAUTH => CURLAUTH_ANY,
			CURLOPT_USERPWD => $user.":".$pass,
			CURLOPT_HTTPHEADER => array(
				"Content-Type: application/json"
			)
		));
		$response_json = curl_exec( $ch );
		if ( curl_errno( $ch ) )
		{
			throw new Exception( curl_error( $ch ), curl_errno( $ch ) );
		}
		if ( curl_getinfo( $ch, CURLINFO_HTTP_CODE ) != 200 )
		{
			return false;
		}
		curl_close( $ch );
		$response_object = json_decode($response_json, true);
		if(array_key_exists('error', $response_object)){
			return false; 		
		}
		return $response_object['result'];
	}

	function register_session($user, $folder){
		return WebSMLJSON(variable_get('websml_url'), variable_get('websml_user'), variable_get('websml_pass'), 'session.register', array($user, $folder));
	};

	function user_session_redirect($user, $folder){
		$res = register_session($user, $folder);
		if($res){
			  header('Location: '.variable_get('websml_url').'/session/'.$res);
		}
	};

	function session_expire($id){
		global $WebSMLUrl, $WebSMLRPCUser, $WebSMLRPCPass;

		return WebSMLJSON(variable_get('websml_url'), variable_get('websml_user'), variable_get('websml_pass'), 'session.expire', array($id)); 	
	};


function websml_menu() {
	$item = array();
	$item["websml"] = array(
			"page callback" => "websml_render",
	        'access arguments' => array('access administration pages'),
	);
    $item['admin/config/content/websml'] = array(
      'title' => 'WebSML configuration',
      'description' => 'Configure the WebSML',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('websml_form'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
    );
	return $item;
}

function websml_form($form, &$form_state) {
  $form['websml_url'] = array(
    '#type' => 'textfield',
    '#title' => t('WebSML URl'),
    '#default_value' => variable_get('websml_url', "http://ruby.eecs.jacobs-university.de:8080/"),
  );

  $form['websml_user'] = array(
    '#type' => 'textfield',
    '#title' => t('Web SML user'),
    '#default_value' => variable_get('websml_user', 'rpc'),
  );

  $form['websml_pass'] = array(
    '#type' => 'textfield',
    '#title' => t('Web SML password'),
    '#default_value' => variable_get('websml_pass', 'pleasechange'),
  );

  return system_settings_form($form);
}

function websml_render() {
	global $user;
	if (!isset($_SESSION["WEBSML_COOKIES"])) {
		$res = register_session($user->name, "/tmp/".$user->name);
		$_SESSION["WEBSML_COOKIES"] = $res;
		return "<iframe style='width:100%; height:100%'  src='".variable_get('websml_url').'/session/'.$res."'></iframe>";
	}
	$res = $_SESSION["WEBSML_COOKIES"];
	return "<iframe style='width:100%; height:100%'  src='".variable_get('websml_url')."'></iframe>";
}

?>