<?php

/**
 * Adds useful blocks for the planetmath theme
 * @author Alex Dumitru <m.dumitru@jacobs-university.de> 
 *
 * Note regarding private articles:
 * At present, there's a slight loophole in the "privacy" feature, since CORRECTIONS
 * and COMMENTS can be posted on private articles, and these secondary objects will
 * show up in the public feed.  In order to fix this, we need to make a suitable
 * join (or filter)...
 */
define('PLANETMATH_BLOCKS_EVERYTHING_ELSE_NUMBER_OF_ITEMS_ON_BLOCK', 10);
define('PLANETMATH_BLOCKS_NUMBER_OF_ITEMS_ON_BLOCK', 7);
define('PLANETMATH_BLOCKS_NUMBER_OF_MESSAGES_ON_BLOCK', 10);
define('PLANETMATH_BLOCKS_NUMBER_OF_USERS_ON_BLOCK', 7);
define('PLANETMATH_BLOCKS_NUMBER_OF_CORRECTIONS_ON_BLOCK', 5);
define('PLANETMATH_BLOCKS_NUMBER_OF_PROBLEMS_ON_BLOCK', 5);
define('PLANETMATH_BLOCKS_NUMBER_OF_SOLUTIONS_ON_BLOCK', 5);
define('PLANETMATH_BLOCKS_NUMBER_OF_REVIEWS_ON_BLOCK', 5);

define('PLANETMATH_BLOCKS_EVERYTHING_ELSE_TYPES',
       serialize(array('correction', 
		       'request',
		       'image',
		       'problem',
		       'solution',
		       'review')));

/**
 * Queries for the block views 
 */
function planetmath_blocks_queryGeneral($type, $sortBy = 'n.created') {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, n.uid, fdb.body_value AS body, u.`name` AS username, n.created, n.changed
    FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id 
    INNER JOIN users u ON u.uid = n.uid
    INNER JOIN field_data_field_published f ON n.nid = f.entity_id
    WHERE n.`type` = :type 
    AND f.field_published_value = 1
    ORDER BY $sortBy DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_ITEMS_ON_BLOCK, array(':type' => $type));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_queryPersonalResponses($uid) {
  $results = db_query("SELECT c.cid, n.nid, n.type, n.title, c.subject, c.uid, c.changed, u.name AS username FROM comment c
      INNER JOIN node n ON n.nid = c.nid      
      INNER JOIN users u ON u.uid = c.uid
      WHERE n.uid = :node_uid AND c.uid != :comment_uid
      ORDER BY c.changed DESC LIMIT 0,".PLANETMATH_BLOCKS_NUMBER_OF_ITEMS_ON_BLOCK, array('node_uid' => $uid, 'comment_uid' => $uid));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;  
}

function planetmath_blocks_queryEverythingElse($sortBy = 'n.changed') {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, n.type as type, n.uid, fdb.body_value AS body, u.`name` AS username, n.created
    FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id 
    INNER JOIN users u ON u.uid = n.uid
    WHERE n.`type` IN (:type) ORDER BY $sortBy DESC LIMIT 0," . PLANETMATH_BLOCKS_EVERYTHING_ELSE_NUMBER_OF_ITEMS_ON_BLOCK, array(':type' => unserialize(PLANETMATH_BLOCKS_EVERYTHING_ELSE_TYPES)));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_queryMessages() {
  $results = db_query("SELECT n.nid AS nid, n.type, n.changed, n.title AS title, n.uid, fdb.body_value AS body, u.`name` AS username, n.created
    FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id 
    INNER JOIN users u ON u.uid = n.uid
    WHERE n.`type` = 'forum' ORDER BY n.changed DESC LIMIT 0," . ceil(PLANETMATH_BLOCKS_NUMBER_OF_MESSAGES_ON_BLOCK / 2));
  $return = array();

  foreach ($results as $result) {
    $return[] = $result;
  }

  $results = db_query("SELECT c.cid, n.nid, n.type, c.subject, c.uid, c.changed, c.name AS username FROM comment c
      INNER JOIN node n ON n.nid = c.nid      
      INNER JOIN users u ON u.uid = c.uid
      ORDER BY c.changed DESC LIMIT 0," . floor(PLANETMATH_BLOCKS_NUMBER_OF_MESSAGES_ON_BLOCK / 2));

  foreach ($results as $result) {
    $return[] = $result;
  }

  usort($return, function($elem1, $elem2) {
            if ($elem1->changed < $elem2->changed) {
              return 1;
            } else if ($elem1->changed > $elem2->changed) {
              return -1;
            }
            return 0;
          });

  return $return;
}

function planetmath_blocks_queryUserList() {
  // jac - for some reason, we were getting a user 0 with no name
  // so I've added an extra line that gets rid of that
  $results = db_query("SELECT u.uid, u.`name`, ut.points
    FROM users u
    LEFT JOIN userpoints_total ut ON ut.uid = u.uid
    WHERE u.name <> ''
    ORDER BY ut.points DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_USERS_ON_BLOCK);

  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_queryCorrections($nid) {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, fdb.body_value AS body, u.`name` AS username, n.created, u.uid AS uid
    FROM node n 
    LEFT JOIN field_data_body fdb ON n.nid = fdb.entity_id 
    LEFT JOIN field_data_field_correction_article fca ON fca.entity_id = n.nid
    INNER JOIN users u ON u.uid = n.uid
    WHERE n.`type` = :type AND fca.field_correction_article_nid = :nid ORDER BY n.created DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_CORRECTIONS_ON_BLOCK, array(':type' => 'correction', ':nid' => $nid));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_queryProblems($nid) {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, u.`name` AS username, n.created, u.uid AS uid
    FROM node n INNER JOIN article_has_problem AS ahp ON (n.nid=ahp.pid) 
    INNER JOIN users u ON u.uid = n.uid 
    WHERE ahp.aid=:nid ORDER BY n.created DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_PROBLEMS_ON_BLOCK, array(':nid' => $nid));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_countProblems($aid) {
  return (db_query("SELECT COUNT(ahp.pid) AS cnt
    FROM article_has_problem AS ahp
    WHERE ahp.aid=:nid LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_PROBLEMS_ON_BLOCK, array(':nid' => $aid))->fetchObject()->cnt > 0) ? true : false;
}


function planetmath_blocks_querySolutions($nid) {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, u.`name` AS username, n.created, u.uid AS uid
    FROM node n INNER JOIN problem_has_solution AS phs ON (n.nid=phs.sid) 
    INNER JOIN users u ON u.uid = n.uid 
    WHERE phs.pid=:nid ORDER BY n.created DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_SOLUTIONS_ON_BLOCK, array(':nid' => $nid));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_countSolutions($pid) {
  return (db_query("SELECT COUNT(phs.sid) AS cnt
    FROM problem_has_solution AS phs
    WHERE phs.pid=:nid LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_SOLUTIONS_ON_BLOCK, array(':nid' => $pid))->fetchObject()->cnt > 0) ? true : false;
}

function planetmath_blocks_queryReviews($nid) {
  $results = db_query("SELECT n.nid AS nid, n.title AS title, u.`name` AS username, n.created, u.uid AS uid
    FROM node n INNER JOIN solution_has_review AS shr ON (n.nid=shr.rid) 
    INNER JOIN users u ON u.uid = n.uid 
    WHERE shr.sid=:nid ORDER BY n.created DESC LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_REVIEWS_ON_BLOCK, array(':nid' => $nid));
  $return = array();
  foreach ($results as $result) {
    $return[] = $result;
  }
  return $return;
}

function planetmath_blocks_countReviews($sid) {
  return (db_query("SELECT COUNT(shr.rid) AS cnt
    FROM solution_has_review AS shr
    WHERE shr.sid=:nid LIMIT 0," . PLANETMATH_BLOCKS_NUMBER_OF_REVIEWS_ON_BLOCK, array(':nid' => $sid))->fetchObject()->cnt > 0) ? true : false;
}

function planetmath_blocks_countCorrectionsPerArticle($nid) {
  return (db_query("SELECT COUNT(n.nid) AS cnt FROM node n
                  INNER JOIN field_data_field_correction_article fca ON fca.entity_id = n.nid
                  WHERE fca.field_correction_article_nid = :nid", array(':nid' => $nid))->fetchObject()->cnt > 0) ? true : false;
}

// We could keep track of the "actual" version id on v.log, since it isn't managed anywhere else.
// Getting all of this imported into the system is going to take some work.
function planetmath_blocks_versions($nid) {
  $results = db_query("SELECT v.log AS version, n.nid AS nid, n.changed AS changed, n.title AS title, u.name AS username, u.uid AS uid 
    FROM node_revision v 
    INNER JOIN node n ON v.nid = n.nid 
    INNER JOIN users u ON u.uid = v.uid
    WHERE n.nid = :nid ORDER BY v.timestamp DESC LIMIT 0,7", array(':nid' => $nid));
  $return = array();
  foreach ($results as $result) {
    if(!is_numeric($result->version)){
      $result->version = 1;
    }
    $return[] = $result;
  }
  return array_reverse($return);
}

function planetmath_blocks_countVersionsPerArticle($nid) {
  return (db_query("SELECT COUNT(n.nid) AS cnt FROM node n
                  INNER JOIN node_revision nv ON nv.nid = n.nid
                  WHERE n.nid = :nid", array(':nid' => $nid))->fetchObject()->cnt > 0) ? true : false;
}

// Since this function is used in a lot of different cases,
// the conditional steps inside are important (in order to
// make everything look good)!
function planetmath_blocks_blockThemeResults($results) {
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  $html = "";
  foreach (array_reverse($results) as $result) {
    if (!isset($result->version)) {
      $title = l($result->title, 'node/' . $result->nid);
    } else {
      // $num = 1 + $result->version - $result->nid;
      $title = l(' (v' . $result->version .')', 'node/' . $result->nid);
    }
    if (!isset($result->changed)) {
      $changed = '';
    } else {
      $changed = ' ' . date('Y-m-d',$result->changed);
    }

    $html .= '<span>' . $title
	              . ' by ' 
                      . l($result->username, 'user/' . $result->uid) 
	              . $changed
                      . '</span><br />';
  }
  //$html .= "</div>";
  return $html;
}

function planetmath_blocks_blockThemeResultsWithDate($results, $sortBy = 'created') {
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  $dates = array();

  $html = "";// '<div style="padding-left:7%;padding-right:10%;padding-bottom:10%;"><br />';
  foreach ($results as $result) {
    if (!isset($result->version)) {
      $result->version = "";
    }

    if ((count($dates) === 0) || 
	strcmp($dates[count($dates) - 1], date('Y-m-d',$result->$sortBy)) != 0)
      {
	array_push($dates,date('Y-m-d',$result->$sortBy));
	$html .= '<span class="block-day-date">'.date('Y-m-d',$result->$sortBy).'</span><br />';
      }

    $html .= '<span >' . l($result->title . ' ' . $result->version, 'node/' . $result->nid) . ' by ' . l($result->username, 'user/' . $result->uid) . '</span><br />';
  }
  if ($sortBy == 'created') {
    $html .= '<div style="text-align:right;">' . l('more', 'articles') . '</div>';
  } else if ($sortBy == 'changed') {
    $html .= '<div style="text-align:right;">' . l('more', 'revisions') . '</div>';
  }
  return $html;
}

function planetmath_blocks_blockThemeEverythingElseWithDate($results, $sortBy = 'created') {
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  $dates = array();

  $html = "";// '<div style="padding-left:7%;padding-right:10%;padding-bottom:10%;"><br />';
  foreach ($results as $result) {
    if (!isset($result->version)) {
      $result->version = "";
    }

    if ((count($dates) === 0) || 
	strcmp($dates[count($dates) - 1], date('Y-m-d',$result->$sortBy)) != 0)
      {
	array_push($dates,date('Y-m-d',$result->$sortBy));
	$html .= '<span class="block-day-date">'.date('Y-m-d',$result->$sortBy).'</span><br />';
      }

    // It would be nice to include the "parent" in some fashion, when it exists, i.e.
    // new solution XX to problem YY.

    $html .= '<span>' . 'new '. $result->type . ': '
              . l($result->title . ' ' . $result->version, 'node/' . $result->nid) 
              . ' by ' . l($result->username, 'user/' . $result->uid) 
              . '</span><br />';
  }

  //$html .= "</div>";
  return $html;
}

function planetmath_blocks_blockThemeUserListResults($results) {
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  // jac - got the right-justified numbers working
  $html = "";
  foreach ($results as $result) {
    $html .= '<span>' . l($result->name, 'user/' . $result->uid) . '</span><span class="block-day-date">' . intval($result->points) . ' </span><br />';
  }
  // jac - link to see more
  $html .= '<div style="text-align:right;">' . l('more', 'scores') . '</div>';
  return $html;
}

function planetmath_blocks_blockThemeMessagesResults($results) {
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  $html = "";// '<div style="padding-left:7%;padding-right:10%;padding-bottom:10%;"><br />';

  foreach ($results as $result) {
    if (isset($result->cid)) {

      // This gives some small visual indication of article nodes vs forum nodes.
      if ($result->type == 'article') {
        $code = 'P';
      } else {
        $code = 'p';
      }

      $html .=  '<span class="block-day-date">' . date('Y-m-d', $result->changed) . '</span>'. '<br /><span class="message-block-item">'. ' [' . l($code, 'node/' . $result->nid) . "] " . l($result->subject, 'node/' . $result->nid, array('fragment' => 'comment-' . $result->cid)) . ' by ' . l($result->username, 'user/' . $result->uid) . '</span><br />';
    } else {
      $html .= '<span class="block-day-date">'. date('Y-m-d', $result->changed) . '</span>' . '<br /><span class="message-block-item">' . l($result->title, 'node/' . $result->nid) . ' by ' . l($result->username, 'user/' . $result->uid) . '</span><br />';
    }
  }
  // jac - link to see more
  $html .= '<div style="text-align:right;">' . l('more', 'talk') . '</div>';
  return $html;
}

function planetmath_blocks_blockThemeMyPersonalResults($results) {
  global $user;
  if(!$user->uid){
    return "<h4>Please log in to view the results</h4>";
  }
  if (empty($results)) {
    return '<h4>No results found</h4>';
  }
  $html = "";// '<div style="padding-left:7%;padding-right:10%;padding-bottom:10%;"><br />';

  foreach ($results as $result) {
    $html .= '<span>' . date('Y-m-d', $result->changed) 
              . " - " . l($result->username, 'user/' . $result->uid)
              . " " . l('replied', 'node/' . $result->nid, 
                           array('fragment' => 'comment-' . $result->cid))
              . ' to ' . l($result->title, 'node/' . $result->nid) . '</span><br />';
  }
 // $html .= "</div>";
  return $html;
}

/**
 * Implementation of hook_block_info 
 */
function planetmath_blocks_block_info() {
  $blocks = array();
  $block_names = array('article', 'request', 'problem', 'solution', 'review', 'forum', 'news', 'correction', 'pversion', 'cross-ref', 'userlist', 'revision', 'message', 'everything-else', 'personal-feed');
  foreach ($block_names as $name) {
    $blocks[$name] = array(
        'info' => t($name),
    );
  }
  return $blocks;
}

// We need to build a real crossRef block!
function planetmath_blocks_crossRefMockBlock() {
  return array(
      'subject' => 'Cross References',
      'content' => 'open problem, amenable, contradiction, relation, equivalence, clear, support, theorems, injective'
  );
}

function planetmath_blocks_block_versions($nid) {
  return array(
      'subject' => 'Versions',
      'content' => planetmath_blocks_blockThemeResults(planetmath_blocks_versions($nid))
  );
}

function planetmath_blocks_block_corrections($nid) {
  return array(
      'subject' => 'Corrections',
      'content' => planetmath_blocks_blockThemeResults(planetmath_blocks_queryCorrections($nid))
  );
}

function planetmath_blocks_block_problems($nid) {
  return array(
      'subject' => 'Problems',
      'content' => planetmath_blocks_blockThemeResults(planetmath_blocks_queryProblems($nid))
  );
}

function planetmath_blocks_block_solutions($nid) {
  return array(
      'subject' => 'Solutions',
      'content' => planetmath_blocks_blockThemeResults(planetmath_blocks_querySolutions($nid))
  );
}

// Reviews should come with some metadata that says whether the problem is correct or not
// and ideally this would be reflected in this block!
function planetmath_blocks_block_reviews($nid) {
  return array(
      'subject' => 'Reviews',
      'content' => planetmath_blocks_blockThemeResults(planetmath_blocks_queryReviews($nid))
  );
}

function planetmath_blocks_block_messages() {
  return array(
      'subject' => 'Latest Messages',
      'content' => planetmath_blocks_blockThemeMessagesResults(planetmath_blocks_queryMessages())
  );
}

function planetmath_blocks_block_revisions() {
  return array(
      'subject' => 'Latest Revisions',
      'content' => planetmath_blocks_blockThemeResultsWithDate(planetmath_blocks_queryGeneral('article', 'n.changed'),'changed')
  );
}

function planetmath_blocks_block_userList() {
  return array(
      'subject' => 'Top Users',
      'content' => planetmath_blocks_blockThemeUserListResults(planetmath_blocks_queryUserList())
  );
}

function planetmath_blocks_block_everythingElse() {
  return array(
      'subject' => 'Everything Else',
      'content' => planetmath_blocks_blockThemeEverythingElseWithDate(planetmath_blocks_queryEverythingElse(),'created')
  );
}

function planetmath_blocks_block_personalFeed() {
  global $user;
  return array(
      'subject' => 'Personal Feed',
      'content' => planetmath_blocks_blockThemeMyPersonalResults(planetmath_blocks_queryPersonalResponses($user->uid))
  );
}

function planetmath_blocks_block_welcome() {
  return array(
      'subject' => 'Welcome!',
      'content' => t("PlanetMath is a virtual community which aims to help make mathematical knowledge more accessible. PlanetMath's content is created collaboratively: the main feature is the mathematics encyclopedia with entries written and reviewed by members. The entries are contributed under the terms of the !ccbysa in order to preserve the rights of authors, readers and other content creators in a sensible way.  We use !latex, the
!linguafranca of the worldwide mathematical community.  You are 
browsing a port of PlanetMath's content into Drupal, which was developed
as part of the Planetary project.  Some release notes are !here.", 
		     array('!ccbysa' =>
			   l("Creative Commons By/Share-Alike License",
			     "http://creativecommons.org/licenses/by-sa/2.0/"),
			   '!latex' => 
			   l("LaTeX", "http://en.wikibooks.org/wiki/LaTeX"),
			   '!linguafranca' => '<em>lingua franca</em>',
			   '!here' => 
			   l("here", "node/86402")
			   )
		     )
	       );
}

/**
 * Implementation of hook_block_view
 */
function planetmath_blocks_block_view($delta = '') {
  $block = array();
  $block_names = array('article' => 'Latest Additions',
		       'request' => 'Requests',
		       'news' => 'News',
		       'forum' => 'Messages');

  foreach ($block_names as $name => $cannonicalName) {
    if ($delta == $name) {
      $block = array(
          'subject' => t(ucfirst($cannonicalName)),
          'content' => planetmath_blocks_blockThemeResultsWithDate(planetmath_blocks_queryGeneral($name),'created')
      );
    }
  }

  //dd("In blocks view");
  //dd(arg(1));
  //dd($delta);

  if ($delta == 'correction') {
    $block = planetmath_blocks_block_corrections(arg(1));
  }

  if ($delta == 'solution') {
    $block = planetmath_blocks_block_solutions(arg(1));
  }
  
  if ($delta == 'problem') {
    $block = planetmath_blocks_block_problems(arg(1));
  }

  if ($delta == 'review') {
    $block = planetmath_blocks_block_reviews(arg(1));
  }

  if ($delta == 'revision') {
    $block = planetmath_blocks_block_revisions();
  }

  if ($delta == 'message') {
    $block = planetmath_blocks_block_messages();
  }

  if ($delta == 'userlist') {
    $block = planetmath_blocks_block_userList();
  }

  if ($delta == 'cross-ref') {
    $block = planetmath_blocks_crossRefMockBlock();
  }

  if ($delta == 'everything-else') {
    $block = planetmath_blocks_block_everythingElse();
  }

  if ($delta == 'pversion') {
    $block = planetmath_blocks_block_versions(arg(1));
  }

  if ($delta == 'personal-feed') {
    $block = planetmath_blocks_block_personalFeed();
  }

  if ($delta == 'welcome') {
    $block = planetmath_blocks_block_welcome();
  }

  return $block;
}

