<?php

/**
 * This function is to replace PHP's extremely buggy realpath().
 * @param string The original path, can be relative etc.
 * @return string The resolved path, it might not exist.
 */
function truepath($path) {
    // whether $path is unix or not
    $unipath = strlen($path) == 0 || $path{0} != '/';
    // attempts to detect if path is relative in which case, add cwd
    if (strpos($path, ':') === false && $unipath)
        $path = getcwd().DIRECTORY_SEPARATOR.$path;
    // resolve path parts (single dot, double dot and double delimiters)
    $path = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $path);
    $parts = array_filter(explode(DIRECTORY_SEPARATOR, $path), 'strlen');
    $absolutes = array();
    foreach ($parts as $part) {
        if ('.'  == $part) continue;
        if ('..' == $part) {
            array_pop($absolutes);
        } else {
            $absolutes[] = $part;
        }
    }
    $path = implode(DIRECTORY_SEPARATOR, $absolutes);
    // resolve any symlinks
    if (file_exists($path) && linkinfo($path) > 0)$path = readlink($path);
    // put initial separator that could have been lost
    $path = !$unipath ? '/'.$path : $path;
    return $path;
}

/**
 * checks if the user is able to access the path @path
 * @return path - normalized path of the file to be accessed
 *         false - if not allowed 
 */
function planetary_repo_access_path($root, $path) {
  $p = truepath($root."/".$path);
  if (strlen($p) == 0)
    return false;
  $prefix = substr($p, 0, strlen($root)); 
  if (strcmp($prefix, $root) == 0)
    return $p;
  else
    return false;
}

/*
 ------------------- LOCAL REPOSITORY ---------------------------
*/

function planetary_repo_local_access_path($path) {
  $root = truepath(variable_get('planetary_repo_local_path', "/tmp/"));
  return planetary_repo_access_path($root, $path);
}

function planetary_repo_is_dir($path) {
  $full_path = planetary_repo_local_access_path($path);
  $ret = is_dir($full_path);
  return $ret;
}

function planetary_repo_local_save($path, $content) {
  $full_path = planetary_repo_local_access_path($path);
  if (!$full_path) 
    return false;
  $f = fopen($full_path, "w");
  fwrite($f, $content);
  fclose($f);
}

function planetary_repo_local_load($path) {
  $full_path = planetary_repo_local_access_path($path);
  $f = fopen($full_path, "r");
  $content = fread($f, 1000000);
  fclose($f);
  return $content;
}

function planetary_repo_local_list($path) {
  $full_path = planetary_repo_local_access_path($path);
  $content = array();
  
  if ($full_path) {
    $handle = opendir($full_path);
    if ($handle) {
      while (false !== ($file = readdir($handle))) {
         $content[] = $file;
      }
      closedir($handle);
    }
  }
  
  return $content;
}

function planetary_repo_local_stat($path) {
  $full_path = planetary_repo_local_access_path($path);
  if ($full_path) {
    if (!file_exists($full_path))
      return null;
    return $handle = stat($full_path);
  }
  return null;
}

function planetary_repo_local_settings(&$element) {
  $element["planetary_repo_local_path"] = array(
      "#type" => "textfield",
      "#title" => "Path to the root directory",
      "#default_value" => variable_get('planetary_repo_local_path', "/tmp/"),
    );
}

/*
 * ----------------- GIT REPOSITORY ---------------------------
 */



function planetary_repo_git_access_path($path) {
  $root = truepath(variable_get('planetary_repo_git_path', "/tmp/"));
  return planetary_repo_access_path($root, $path);
}

function planetary_repo_git_settings(&$element) {
  $element["planetary_repo_git_path"] = array(
      "#type" => "textfield",
      "#title" => "Path to the checked out git repository",
      "#default_value" => variable_get('planetary_repo_git_path', "/tmp/"),
    );

  $element["planetary_repo_git_exec"] = array(
      "#type" => "textfield",
      "#title" => "Path to the git executable",
      "#default_value" => variable_get('planetary_repo_git_exec', "/usr/bin/git"),
    );
}

function planetary_repo_git_pull($rel_path) {
  $exec = variable_get('planetary_repo_git_exec', "/usr/bin/git");
  $base_path = variable_get('planetary_repo_git_path'); 
  $path = dirname($base_path . $rel_path);
  $ret = shell_exec("cd $path; git pull 2>&1");
}

function planetary_repo_git_push($rel_path) {
  global $user;
  $uname = $user->name;
  $exec = variable_get('planetary_repo_git_exec', "/usr/bin/git");
  $base_path = variable_get('planetary_repo_git_path');
  $path = dirname($base_path . $rel_path);
  $filename = basename($rel_path);
  shell_exec("cd $path; git add $filename; git commit -m 'change by user $uname'; git push origin master ");
}

function planetary_repo_git_save($path, $content) {
  $full_path = planetary_repo_git_access_path($path);
  if (!$full_path) 
    return false;
  $f = fopen($full_path, "w");
  fwrite($f, $content);
  fclose($f);
  planetary_repo_git_push($path);
}

function planetary_repo_git_load($path) {
  planetary_repo_git_pull($path);
  $full_path = planetary_repo_git_access_path($path);
  $f = fopen($full_path, "r");
  $content = fread($f, 1000000);
  fclose($f);
  return $content;
}

function planetary_repo_git_list($path) {
  planetary_repo_git_pull($path);
  $full_path = planetary_repo_git_access_path($path);
  $content = array();
  if ($full_path) {
    $handle = opendir($full_path);
    if ($handle) {
      while (false !== ($file = readdir($handle))) {
         $content[] = $file;
      }
      closedir($handle);
    }
  }
  return $content;
}

function planetary_repo_git_stat($path) {
  planetary_repo_git_pull($path);
  $full_path = planetary_repo_git_access_path($path);
  if ($full_path) {
    if (!file_exists($full_path))
      return null;
    return $handle = stat($full_path);
  }
  return null;
}


function planetary_repo_repo_provider() {
  return array(
    "local" => array(
        "label" => "Local File System",
        "settings" => 'planetary_repo_local_settings',
        "save" => 'planetary_repo_local_save',
        "load" => 'planetary_repo_local_load',
        "list" => 'planetary_repo_local_list',
        "stat" => 'planetary_repo_local_stat',
      ),
    "git" => array(
        "label" => "Git File System",
        "settings" => 'planetary_repo_git_settings',
	"save" => 'planetary_repo_git_save',
        "load" => 'planetary_repo_git_load',
        "list" => 'planetary_repo_git_list',
        "stat" => 'planetary_repo_git_stat',
      )
    );
}

function planetary_repo_menu() {
  // create page where the paths can be configured
  $items = array();
  $items['admin/config/content/repo'] = array(
    'title' => 'Repositories configuration',
    'description' => 'Configure the VFS to connect to',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('planetary_repo_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/content/repo/sync'] = array(
    'title' => 'Sync Repository',
    'description' => 'Sync the VFS to connect to',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('planetary_repo_sync_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function planetary_repo_sync_form($form, $form_state) {
   $form = array();
   
   return $form;
}

function planetary_repo_save_file($path, $contents) {
  $current = variable_get('planetary_repo_provider', null);
  if ($current) {
    $providers = module_invoke_all("repo_provider");
    $providers[$current]["save"]($path, $contents);
  };
}

function planetary_repo_stat_file($path) {
  $current = variable_get('planetary_repo_provider', null);
  if ($current) {
    $providers = module_invoke_all("repo_provider");
    return $providers[$current]["stat"]($path);
  };
}

function planetary_repo_load_file($path) {
  $current = variable_get('planetary_repo_provider', null);
  if ($current) {
    $providers = module_invoke_all("repo_provider");
    return $providers[$current]["load"]($path);
  };
}

function planetary_repo_list($path) {
  $current = variable_get('planetary_repo_provider', null);
  if ($current) {
    $providers = module_invoke_all("repo_provider");
    return $providers[$current]["list"]($path);
  };
}

function planetary_repo_config_form($form, &$form_state) {
  $providers = module_invoke_all("repo_provider");
  $options = array();
  foreach ($providers as $id=>$provider) {
    $options[$id] = $provider["label"];
  }
  $current = variable_get('planetary_repo_provider', null);
  $form['planetary_repo_provider'] = array(
    '#type' => 'select',
    '#title' => t('What kind of repository should be used'),
    '#default_value' => $current,
    '#options' => $options,
    '#description' => t('Determine if we are using sTeX or normal LaTeX'),
  );
  if ($current) {
    $form['settings'] = array();
    $providers[$current]["settings"]($form['settings']);
  }
  return system_settings_form($form);
}

/*
 * hook_field_info
 */
function planetary_repo_field_info() {
  return array(
    'vfs_file' => array(
      'label' => t('VFS file'),
      'description' => t('File residing on a Virtual File System'),
      'default_widget' => 'vfs_widget',
      'default_formatter' => 'vfs_formatter'
    )
  );
}

function planetary_repo_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['path'])) {
      // TODO: write code to check that the path inside the VFS exists
    }
  }
}

function planetary_repo_field_formatter_info() {
  return array(
   // This formatter changes the background color of the content region.
    'vfs_formatter' => array(
      'label' => t('Formatter of VFS content'),
      'field types' => array('vfs_file'),
    ),
  );
}

function planetary_repo_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    // This formatter simply outputs the field as text and with a color.
    case 'vfs_formatter':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          // We create a render array to produce the desired markup,
          // "<p style="color: #hexcolor">The color code ... #hexcolor</p>".
          // See theme_html_tag().
          '#type' => 'html_tag',
          '#tag' => 'p',
          '#value' => t('Path is @code', array('@code' => $item['path'])),
        );
      }
      break;
  }

  return $element;
}

function planetary_repo_field_widget_info() {
  return array(
    'vfs_widget' => array(
      'label' => t('VFS widget'),
      'field types' => array('vfs_file'),
    ),
  );
}

function planetary_repo_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $path = isset($items[$delta]['path']) ? $items[$delta]['path'] : '';
  $filter = isset($items[$delta]['filter']) ? $items[$delta]['filter'] : '';
  $widget = $element;
  $widget['#delta'] = $delta;
  $content = planetary_repo_load_file($path);

  switch ($instance['widget']['type']) {
    case 'vfs_widget':
      $widget['#element_validate'] = array('planetary_repo_field_widget_validate');
      $widget["#type"] = "fieldset";
      $widget["data"] = array(
             "path" => array(
               "#type" => "textfield",
               "#title" => "File path",
               "#default_value" => $path
             ),
             "content" => array(
              '#title' => t('Editor'),
              '#type' => 'text_format',
              '#tree' => true,
              '#default_value' => $content,
              '#rows' => 20,
              '#format' => $filter,
              )
        );
      $widget["filter"] = array(
              '#type' => 'hidden',
              );
      $widget["path"] = array(
              '#type' => 'hidden',
              );
      break;
  }

  return $widget;
}

function planetary_repo_field_widget_validate($element, &$form_state) {
  $delta = $element['#delta']; // TODO: Isn't there a better way to find out which element?
  $field = $form_state['field'][$element['#field_name']][$element['#language']]['field'];
  $field_name = $field['field_name'];
  if (isset($form_state['values'][$field_name][$element['#language']][$delta])) {
    $values = $form_state['values'][$field_name][$element['#language']][$delta];
    planetary_repo_save_file($values["data"]["path"], $values["data"]["content"]["value"]);
    form_set_value($element["filter"], $values["data"]["content"]["format"], $form_state);
    form_set_value($element["path"], $values["data"]["path"], $form_state);
  }
}

function planetary_repo_field_is_empty($item, $field) {
  return empty($item['path']);
}

