<?php

/**
 * Implements hook_views_api
 * declared API version used for views 
 */
function oaff_views_views_api() {
  return array(
    'api' => "3.0",
  );
}

function oaff_views_menu() {
  $items = array();
  $items['oaff-broken-docs'] = array(
    'title' => "Broken Documents",
    'page callback' => 'oaff_views_broken_nodes',
    'access callback' => true,
    'type' => MENU_CALLBACK,

  );
  $items['oaff-add-doc'] = array(
    'title' => "Add Document",
    'page callback' => 'oaff_views_add_doc',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  $items['oaff-sort-unpopularity'] = array(
    'title' => "Unpopular entries",
    'page callback' => 'todo',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  $items['oaff-show-questions'] = array(
    'title' => "User Questions",
    'page callback' => 'todo',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function oaff_views_add_doc() {
  return drupal_get_form('oaff_views_add_doc_form');
}

function todo() {
  return "<p> Coming soon...</p>";
}

function oaff_views_add_doc_form() {
  $form = array();

  $form['archive'] = array(
    '#type' => 'textfield',
    '#title' => 'Archive',
    '#required' => true,
  );
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => 'Module Name',
    '#required' => true,
  );
  $form['body'] = array(
    '#type' => 'text_format',
    '#title' => 'Document Body',
    '#required' => true,
  );

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Create Document')
  );
  $form['#submit'] = array('oaff_views_add_doc_callback');
  return $form;
}

function oaff_views_add_doc_callback($form, &$form_state) {
  $archive = $form_state['values']['archive'];
  $title = $form_state['values']['title'];
  $body = $form_state['values']['body'];

  $oaff_config = variable_get('oaff_config');
  $format = $oaff_config['formats'][$archive];
  $extension = $oaff_config['extensions'][$format];
  $location = $archive . '/source/' . $title . "." . $extension;
  planetary_repo_save_file($location, $body);
  drupal_set_message("Created document " . $title);
  $nid = oaff_create_oaff_doc($location, $archive);
  $form_state['redirect'] = 'node/'. $nid;
}


function oaff_views_broken_nodes() {
  $query = db_select('node', 'n');
  $query->join('oaff_errors', 'e', 'e.nid = n.nid');
  $query->join('users', 'u', 'u.uid = n.uid');
  $results = $query    
    ->fields('n', array('title', 'nid', 'created'))
    ->fields('e', array('status', 'infos', 'warnings', 'errors', 'fatals'))
    ->fields('u', array('name', 'uid'))
    ->execute()
    ->fetchAll();
  $msg = "<div>";
  usort($results, function($a, $b) {
      return ($a->status < $b->status);
    });
  foreach ($results as $entry) {
    $msg .= '<div class="views-row">';
    $msg .= '<div typeof="sioc:Item foaf:Document" about="/~mihnea/planetary/?q=http%3A//docs.omdoc.org/smglom/copelanderdoesconstant.de.omdoc" class="node node-oaff_doc node-teaser contextual-links-region" id="node-' . $entry->nid . '">';
    $msg .= '<h2> <a href="?q=/node/' . $entry->nid . '">' . $entry->title. '</a></h2>';
    $msg .= '<span class="submitted"><span >' . date("D M j, Y, g:i a", $entry->created) . ' &mdash; <a  class="username" title="View user profile." href="/~mihnea/planetary/?q=user/' . $entry->uid . ' ">' . $entry->name . '</a></span></span>';
    $msg .= '<div class="clearfix">
          <div class="links"><ul class="links inline"><li><span>';
    if ($entry->infos == 1) {
      $msg .= '<span style="color:#9999FF">' . $entry->infos . " info</span>,"; 
    } elseif ($entry->infos != 0) {
      $msg .= '<span style="color:#9999FF">' . $entry->infos . " infos</span>,"; 
    } 
    if ($entry->warnings == 1) {
      $msg .= '<span style="color:#BBBB11">' . $entry->warnings . " warning</span>,";
    } elseif ($entry->warnings != 0) {
      $msg .= '<span style="color:#BBBB11">' . $entry->warnings . " warnings</span>,";
    } 
    if ($entry->errors == 1) {
      $msg .= '<span style="color:#FF6666">' . $entry->errors . " error</span>,";
    } elseif ($entry->errors != 0) {
      $msg .= '<span style="color:#FF6666">' . $entry->errors . " errors</span>,";
    } 
    if ($entry->fatals == 1) {
      $msg .= '<span style="color:#FF2222">' . $entry->fatals . " fatal</span>,";
    } elseif ($entry->fatals != 0) {
      $msg .= '<span style="color:#FF2222">' . $entry->fatals . " fatals</span>,";
    }
    $msg = substr($msg, 0, -1); // removing last comma
    $msg .= "</span></li>";

    $msg .= '<li ><a title="copelanderdoesconstant" href="?q=/node/' . $entry->nid . '">See details</a></li></ul></div></div>';
    $msg .= "</div></div>";
  }
  $msg .= "</div>";
  return $msg;
}


/**
 * implements hook_views_default_views
 * declares views, using view API
 * Currently: 
 *    oaff_broken_docs_view => view of all oaff nodes that have compilation errors
 */
function oaff_views_views_default_views() {
  $views = array();

  $view = new view();
  $view->name = 'oaff_latest_updates';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'oaff-latest-updates';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = false; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Latest Updates';
  $handler->display->display_options['use_more_always'] = false;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['style_plugin'] = 'list';
  $handler->display->display_options['row_plugin'] = 'node';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = false;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = false;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['exclude'] = true;
  $handler->display->display_options['fields']['nid']['alter']['alter_text'] = true;
  $handler->display->display_options['fields']['nid']['alter']['text'] = 'node/[nid]';
  /* Sort criterion: Content revision: Updated date */
  $handler->display->display_options['sorts']['timestamp']['id'] = 'timestamp';
  $handler->display->display_options['sorts']['timestamp']['table'] = 'node_revision';
  $handler->display->display_options['sorts']['timestamp']['field'] = 'timestamp';
  $handler->display->display_options['sorts']['timestamp']['order'] = 'DESC';
  $handler->display->display_options['sorts']['timestamp']['expose']['label'] = 'Updated date';
  /* Sort criterion: Content: Last comment time */
  $handler->display->display_options['sorts']['last_comment_timestamp']['id'] = 'last_comment_timestamp';
  $handler->display->display_options['sorts']['last_comment_timestamp']['table'] = 'node_comment_statistics';
  $handler->display->display_options['sorts']['last_comment_timestamp']['field'] = 'last_comment_timestamp';
  $handler->display->display_options['sorts']['last_comment_timestamp']['order'] = 'DESC';
  $handler->display->display_options['sorts']['last_comment_timestamp']['expose']['label'] = 'Last comment time';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = false;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'glossary' => 'glossary',
    'oaff_doc' => 'oaff_doc',
  );

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page');
  $handler->display->display_options['path'] = 'oaff-latest-updates';

  $views[$view->name] = $view;
  return $views;
}
