<?php
/**
* Implements hook_preprocess_node
*
* @param &$variables
*/
function planetaryinfo_preprocess_node(&$variables = '') {

   $node = $variables['node'];

   unset( $node->body );
   unset( $node->rdf_mapping );

   global $user;

   $data = array(
      'documentRoot' => $_SERVER['DOCUMENT_ROOT'],
      'root'         => getDir( $_SERVER['PHP_SELF'] ),
      'user'         => $user,
      'node'         => $node
   );
   
   $dataObject = @json_encode( $data );

   drupal_add_js( <<<JS
      jQuery(function(){
         $.extend( Drupal, { extraInfo : $dataObject } );
      });
JS
      , 
      array( 'type' => 'inline', 'weight' => 0 ) 
   );
   
}

function getDir( $str ){
   return substr( $str, 0, strrpos( $str, "/" ) ) . '/';
}

