<?php

/* API functions */

/**
 * API function for adding a module to JOBAD, currently JOBAD wide, configuring per-instance behaviour is a //TODO
 * @param $file location of the js file implementing the module as string URI
 * @param $id the name (id) of the module, to be used when loading the module to an instance
 * @param $params the paremters to pass to the modle should be an array
 */
function jobad_add_module($file, $id, $params = array() ) {
  $modules_array = variable_get('JOBADModulesArray');
  $modules_array[$id] = array($file, $params);
  variable_set('JOBADModulesArray', $modules_array);
}

/**
 * API function for adding an element to the sidebar
 */

function jobad_add_to_sidebar($instance, $element, $options) {
  $str = '$(function(){'; //run this once DOM is ready
  $str .= $instance . ".Sidebar.registerNotification(" . $element . ", { \n";

  if (array_key_exists("class", $options)) {
    $str .= '"class": "' . $options["class"] . "\",\n";
  }
  if (array_key_exists("text", $options)) {
    $str .= '"text": "' . $options["text"] . "\",\n";
  }
  if (array_key_exists("icon", $options)) {
    $str .= '"icon": "' . $options["icon"] . "\",\n";
  }
  if (array_key_exists("click", $options)) {
    $str .= '"click": ' . $options["click"] . ",\n";
  }
  if (array_key_exists("menu", $options)) {
    $str .= '"menu": ' . $options["menu"] . ",\n";
  }

  $str .= "});\n";
  $str .= '});';
  drupal_add_js($str, 'inline');
}


/**
 * API function for initializing JOBAD
 * @param $where An Optional CSS selector for where to put the JOBAD Instance. 
 * @return instance name
 */
function jobad_initialize($where = NULL) {
  if (! variable_get('JOBADLoaded')) {
    jobad_init_libs();
    variable_set('JOBADLoaded', true);
    $config_str = 'JOBAD.config.BootstrapScope = "bootstrap"';
    drupal_add_js($config_str, 'inline');
  }

  jobad_init_modules();
  $nr = variable_get('JOBADInstances') + 1;

  if($where == NULL){
    $where = "#JOBAD" . $nr; 
  }

  $inst_id = jobad_init_instance($nr, $where);
  variable_set('JOBADInstances', $nr);
  return $inst_id;
}

/* hooks and helper functions */

/**
 * implements hook_boot() called on page load, initializes variables
 */
function jobad_boot() {
  variable_set('JOBADLoaded', false);
  variable_set('JOBADInstances', 0);
  variable_set('JOBADModulesArray', array());
  variable_set('JOBADJSBuffer', ''); //buffers js to be added to page, is dumped on every jobad_initialize call
}

/**
 * helper function for loading jobads css and js files
 */
function jobad_init_libs() {
  //init the libraries
  drupal_add_library('system', 'ui.dialog');
  drupal_add_library('system', 'ui.tabs');
  drupal_add_library('system', 'ui.spinner');
  drupal_add_library('system', 'ui.menu');

  libraries_load("jobad");
}

/**
 * Helper function for loading jobad module files
 */
function jobad_init_modules() {
  $modules = variable_get('JOBADModulesArray');
  foreach($modules as $id => $options) {
    jobad_register_module($options[0]);
  }
}

/**
 * helper function for registering a module (i.e. loading the relevant js file)
 * @param $file location of the js file implementing the module as string URI
 */
function jobad_register_module($file) {
  drupal_add_js($file, array('type' => 'file', 'weight' => 22));
}

/**
 * helper function for loading a module with a JOBAD instance
 * @param $jobad_instance the id of the JOBAD instance
 * @param $module_id the id of the JOBAD module
 */
function jobad_load_module($jobad_instance, $module_id, $params) {
  return $jobad_instance . '.modules.load("' . $module_id . '" ,[], ' . json_encode($params). '); ';
}

/**
 * helper function for initializing a new JOBAD instance on a page
 * @param $nr the number of this instance (reset on page (re)load), used to generate unique instance id
 * @param $where Where to put the JOABD Instance. 
 * @return $name the id (name) of the jobad instance
 */

function jobad_init_instance($nr, $where) {
    //inline
  $name = 'JOBAD' . $nr;
    $str = 'var ' . $name . ', ' . $name .'_element;
    jQuery(function(){
      ' . $name .'_element = jQuery("' . $where . '");
      if(' . $name .'_element.length == 0){ return; } //to not have errors from JOBAD
      ' . $name . ' = new JOBAD(' . $name .'_element);
    ';
    
  //loading modules
  $str .= jobad_register_module("sites/all/libraries/jobad/modules/core/jobad/jobad.config.js");
  $str .= jobad_load_module($name, "jobad.config", array());
  $modules = variable_get('JOBADModulesArray');
    foreach($modules as $id => $options) {
    $str = $str . '    ' . jobad_load_module($name, $id, $options[1]);
  }
  $str = $str. '
      ' . $name . '.Setup();
    });
  ';

  drupal_add_js($str, array('type' => 'inline', "weight" => 25));
  return $name;
}
