<?php 

function tntbase_import_menu() {
	$item = array();
	$item["admin/config/content/tntbase_import"] = array(
   			'title' => 'TNTBase import document',
    		'description' => 'Import TNTBase articles',
    		'access arguments' => array('access administration pages'),
    		'type' => MENU_NORMAL_ITEM,
    		'page callback' => 'drupal_get_form',
			'page arguments' => array('tntbase_import_page'),
	);

	$item["admin/config/content/tntbase_update"] = array(
	   		'title' => 'TNTBase synchronise',
	    	'description' => 'Synchronise TNTBase articles',
	    	'access arguments' => array('access administration pages'),
	    	'type' => MENU_NORMAL_ITEM,
    		'page callback' => 'drupal_get_form',
			'page arguments' => array('tntbase_update_page'),
	);
	return $item;
}

function tntbase_update_page($form, &$form_status) {
	$taxonomy = array();
	foreach (taxonomy_get_vocabularies() as $terms) {
		foreach (taxonomy_get_tree($terms->vid) as $term) {
			$taxonomy[$term->tid]=$term->name;
		}
	}
	$form["taxonomy_update"] = array(
		'#type' => 'select', 
		'#title'=>'Please select which pages should be updated based on a taxonomy term',
		'#options' => $taxonomy,
	);
	$form["taxonomy_submit"] = array(
		'#type' => 'submit',
		'#submit' => array('tntbase_update_taxonomy_based'),
		'#value' => 'Update'
	);
	return $form;	
}

function tntbase_update_taxonomy_based($form, &$form_state) {
	$tid = $form_state["values"]["taxonomy_update"];
	$nids = taxonomy_select_nodes($tid, false);
	tntbase_sync_nodes($nids);
}

function tntbase_import_page($form, &$form_status) {
	
	$form["TNTPath"] = array(
			'#type' => 'textfield', 
			'#title'=>'Please enter the path of the file to import from TNTBase',
			'#default_value' => '/slides/gencs/notes/notes.tex'
	);
	$form["TNTImport"] = array(
			'#type' => 'submit',
			'#value' => 'import',
			'#submit' => array('tntbase_import_doImport'),
	);
	return $form;
}

function tntbase_import_doImport($form, &$form_state) {
	$path = $form_state["values"]["TNTPath"];
	$nid = tntbase_node_getNodeFromPath($path);
	if (isset($nid)) {
		$nodes = array($nid); 
		tntbase_sync_nodes($nodes);
		return $nid;
	} else {
		$nid = tntbase_node_import($path);
		return $nid;
	}
	
}

?>