<?php 

function tntbase_import_menu() {
	$item = array();
	$item["content/tntbase/import"] = array(
			'page callback' => 'drupal_get_form',
		    'page arguments' => array('tntbase_import_page'),
		    'access callback' => TRUE,
		    'type' => MENU_CALLBACK,
	);

	$item["content/tntbase/update"] = array(
				'page callback' => 'drupal_get_form',
			    'page arguments' => array('tntbase_update_page'),
			    'access callback' => TRUE,
			    'type' => MENU_CALLBACK,
	);
	return $item;
}

function tntbase_update_page($form, &$form_status) {
	$taxonomy = array();
	foreach (taxonomy_get_vocabularies() as $terms) {
		foreach (taxonomy_get_tree($terms->vid) as $term) {
			$taxonomy[$term->tid]=$term->name;
		}
	}
	$form["taxonomy_update"] = array(
		'#type' => 'select', 
		'#title'=>'Please select which pages should be updated based on a taxonomy term',
		'#options' => $taxonomy,
	);
	$form["taxonomy_submit"] = array(
		'#type' => 'submit',
		'#submit' => array('tntbase_update_taxonomy_based'),
		'#value' => 'Update'
	);
	return $form;	
}

function tntbase_update_taxonomy_based($form, &$form_state) {
	$tid = $form_state["values"]["taxonomy_update"];
	$nids = taxonomy_select_nodes($tid, false);
	tntbase_sync_nodes($nids);
}

function tntbase_import_page($form, &$form_status) {
	
	$form["TNTPath"] = array(
			'#type' => 'textfield', 
			'#title'=>'Please enter the path of the file to import from TNTBase',
			'#default_value' => '/slides/gencs/notes/notes.tex'
	);
	$form["TNTImport"] = array(
			'#type' => 'submit',
			'#value' => 'import',
			'#submit' => array('tntbase_import_doImport'),
	);
	return $form;
}

function tntbase_import_doImport($form, &$form_state) {
	$path = $form_state["values"]["TNTPath"];
	$nid = tntbase_node_getNodeFromPath($path);
	if (isset($nid)) {
		$nodes = array($nid); 
		tntbase_sync_nodes($nodes);
		drupal_set_message("Node id=".$nid." was updated!");
	} else {
		$nid = tntbase_node_import($path);
		drupal_set_message("Node saved and has id ".$nid);
	}
	
}

?>